<div class="form-group">
  <? ### UChicago customization ### ?>
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Barcode')?>:</label>
  <? ### ./UChicago customization ### ?>
  <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" autofocus autocomplete="username"/>
</div>
<div class="form-group">
  <? ### UChicago customization ### ?>
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('PIN')?>:</label>
  <? ### ./UChicago customization ### ?>
  <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control" autocomplete="current-password"/>
</div>
