<div class="no-cnet-login">
    <div class="form-group">
      <label class="col-sm-9" for="login_username"><?=$this->transEsc('Barcode')?>:</label>
      <div class="col-sm-9">
        <input type="text" name="username" id="login_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-9" for="login_password"><?=$this->transEsc('PIN')?>:</label>
      <div class="col-sm-9">
        <input type="password" name="password" id="login_password" class="form-control"/>
      </div>
    </div>
</div>
