<?php foreach ($data as $d):?>
  <?php foreach ($d['displayData'] as $key => $val):?>
    <?php if (!empty($d['linkData'][$key])): ?>
       <?php if ($d['areFasts'][$key] === true): ?>
         <a href="/vufind/Search/Results?lookfor=<?=urlencode($d['linkData'][$key]) . '&type=Subject'?>"><?=$val?></a><br/>
       <?php else: ?>
         <a href="/vufind/Alphabrowse/Home?source=topic&from=<?=urlencode($d['linkData'][$key])?>"><?=$val?></a><br/>
       <?php endif; ?>
    <?php else: ?>
        <?=$val?><br/>
    <?php endif; ?>
  <?php endforeach; ?>
  <?php foreach ($d['altData'] as $altVal):?>
    <?=$altVal?><br/>
  <?php endforeach; ?>
<?php endforeach; ?>
