<?php $searchRoute = $this->searchOptions($this->driver->getSearchBackendIdentifier())->getSearchAction(); ?>
<?php
if ($searchRoute === 'search-results') { // override search-results with author module
  ### UChicago customization ###
  ### Change author urls to alphabrowse ###
  echo $this->url('alphabrowse-home')?>?source=author&from=<?=urlencode($this->lookfor);
  ### ./UChicago customization ###
} else {
  echo $this->url($searchRoute) . '?lookfor=%22' . urlencode($this->lookfor) . '%22&amp;type=Author';
}
