<?php $searchRoute = $this->searchOptions($this->driver->getSourceIdentifier())->getSearchAction(); ?>
<?php if ($searchRoute === 'search-results'): // override search-results with author module ?>
  <? ### UChicago customization ### ?>
  <? ### Change author urls to alphabrowse ### ?>
  <?=$this->url('alphabrowse-home')?>?source=author&from=<?=urlencode($this->lookfor)?>
  <? ### ./UChicago customization ### ?>
<?php else: ?>
  <?=$this->url($searchRoute)?>?lookfor=%22<?=urlencode($this->lookfor)?>%22&amp;type=Author
<?php endif; ?>
