<?php
  /* This code is only needed until we upgrade to VuFind 11 or later. Look at closed issue #169 and the pull request for branch 169-backport-rate-limiter-and-cloudfare-turnstile to see the full list of files that can be removed after we upgrade. */
  $this->headScript()->appendFile($jsLibraryUrl, 'text/javascript', ['defer' => '', 'async' => '']);
  $js = <<<JS
      function turnstileChallengeEnded(token) {
          document.getElementById('turnstile_token').setAttribute('value', token);
          document.getElementById('turnstile_form').submit();
      }
      JS;
?>
<?=$this->inlineScript()->appendScript($js)?>

<div
    class="cf-turnstile"
    data-sitekey="<?=$this->escapeHtml($siteKey)?>"
    data-callback="turnstileChallengeEnded"
    data-error-callback="turnstileChallengeEnded"
></div>
<form id="turnstile_form" method="post" action="<?=$this->url('turnstile-verify')?>">
    <input id="turnstile_token" name="token" type="hidden">
    <input name="policyId" type="hidden" value="<?=$this->escapeHtml($policyId)?>">
    <input name="destination" type="hidden" value="<?=$this->escapeHtml($destination)?>">
    <input name="hash" type="hidden" value="<?=$this->escapeHtml($hash)?>">
</form>
