<?php
    $previews = isset($this->config->Content->previews)
        ? explode(',', $this->config->Content->previews) : [];
    if (!empty($previews)) {
        $idClasses = $this->record($this->driver)->getPreviewIds();
        // If we found at least one identifier, we can build the placeholder HTML:
        $html = '';
        if (!empty($idClasses)) {
            // Convert to string:
            $idClasses = implode(' ', $idClasses);

            // Loop through previews and build appropriate HTML:
            foreach ($previews as $current) {
                switch (trim(strtolower($current))) {
                case 'google':
                    $name = 'Google Books';
                    $divClass = 'googlePreviewDiv';
                    $linkClass = 'previewGBS';
                    $icon = '<i class="fa fa-google"></i>';
                    $text = 'Google Books ';
                    $tooltip = '<div class="arrow-left"></div><span><img src="https://www.google.com/intl/' . $this->layout()->userLang . '/googlebooks/images/gbs_preview_button1.png" alt="' . $this->transEsc('Preview') . '"/> </span>';
                    break;
                case 'openlibrary':
                    $name = 'Open Library';
                    $divClass = 'olPreviewDiv';
                    $linkClass = 'previewOL';
                    $icon = '';
                    $text = 'Open Library';
                    $tooltip = '';
                    break;
                case 'hathitrust':
                    $name = 'HathiTrust';
                    $divClass = 'hathiPreviewDiv';
                    $linkClass = 'previewHT';
                    $icon = '<img src="' . $this->imageLink('hathitrustFavicon.png') . '" alt="' . $this->transEsc('Preview') . '" />';
                    $text = 'HathiTrust Digital Library';
                    $tooltip = '';
                    break;
                default:
                    $name = $divClass = $linkClass = $icon = $text = false;
                    break;
                }
                if ($name) {
                    $title = '';
                    $html .= '<div class="' . $divClass .'">'
                        . '<a title="' . $title . '" class="eLink hidden tool ' . $linkClass . ' ' . $idClasses . '" target="_blank">'
                        . $text 
                        . $tooltip
                        . '</a>' 
                        . '</div>';
                }
            }

            // javascript included in previewdata template
            if (!empty($html)) {
                echo $html;
            }
        }
    }
?>
