<?   /* This file will be very different from it's bootstrap counterpart
        because it is driven by our custom SolrMarcPhoenix record driver
        Only diff stuff after <div class="last"> - brad*/

     // Set up convenience variables:
     $siteUrl = null; //set here to avoid a php warning, however, the value of this comes from the config files and is passed through theme.config.php
?>

<?
  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }
?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <div class="col-sm-9 info-col">

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped">
      <caption><?=$this->transEsc('Bibliographic Details')?></caption>
      <? $this->MarcFields()->returnMarcData('top', $siteUrl); ?>
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <?
            $containerSource = $this->driver->getSourceIdentifier();
            $containerID = $this->driver->getContainerRecordID();
          ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <!--<tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>-->
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <a class="tag-record btn btn-link pull-right flip" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" data-lightbox>
              <i class="fa fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Add Tag')?>
            </a>
            <?=$this->context($this)->renderInContext('record/taglist', array('tagList'=>$tagList, 'loggedin'=>$loggedin)) ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>

    <?/* Display Additional Details */?>
    <table id="top-hidden" class="table table-striped">
      <? $this->MarcFields()->returnMarcData('top-hidden'); ?>
    </table>
    <?/* End Additional Details */?>
  </div><!--/.col-sm-9-->

  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?//=$this->record($this->driver)->getPreviews()?>
    <?=$this->record($this->driver)->getPreviewData()?>
  </div><!--/.col-sm-3-->
</div><!--/.row-->
