<?   /* This file will be very different from it's bootstrap counterpart
        because it is driven by our custom SolrMarcPhoenix record driver
        Only diff stuff after <div class="last"> - brad*/

     // Set up convenience variables:
     $siteUrl = null; //set here to avoid a php warning, however, the value of this comes from the config files and is passed through theme.config.php
?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <div class="col-sm-9 info-col">

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <?
      $formatter = $this->recordDataFormatter();
      /* Allowed fields from core. These are core functions/fields
         that we want to add to our custom output from MarcFields*/
      $allowed = ['Related Items'];
      $defaultCoreFields = $formatter->getDefaults('core');
      foreach (array_keys($defaultCoreFields) as $field) {
          if (!in_array($field, $allowed)) {
              unset($defaultCoreFields[$field]);  
          }  
      }
      $coreFields = $formatter->getData($driver, $defaultCoreFields);
    ?>
    <table class="table table-striped">
      <caption><?=$this->transEsc('Bibliographic Details')?></caption>
      <? $this->MarcFields()->returnMarcData('top', $siteUrl); ?>
        <? foreach ($coreFields as $key => $value): ?>
          <tr><th><?=$this->transEsc($key)?>:</th><td><?=$value?></td></tr>
        <? endforeach; ?>
    </table>
    <?/* End Main Details */?>

    <?/* Display Additional Details */?>
    <table id="top-hidden" class="table table-striped">
      <? $this->MarcFields()->returnMarcData('top-hidden'); ?>
    </table>
    <?/* End Additional Details */?>
  </div><!--/.col-sm-9-->

  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?//=$this->record($this->driver)->getPreviews()?>
    <?=$this->record($this->driver)->getPreviewData()?>
  </div><!--/.col-sm-3-->
</div><!--/.row-->
