<?   /* This file will be very different from it's bootstrap counterpart
        because it is driven by our custom SolrMarcPhoenix record driver
        Only diff stuff fter <div class="last"> - brad*/

     // Set up convenience variables:
     $siteUrl = null; //set here to avoid a php warning, however, the value of this comes from the config files and is passed through theme.config.php
?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-9">
    <? //Not sure what this does, leaving it in case we want it - brad ?>
    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped">
      <caption><?=$this->transEsc('Bibliographic Details')?></caption>
      <? $this->MarcFields()->returnMarcData('top', $siteUrl); ?>
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <? $containerID = $this->driver->getContainerRecordID(); ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("VuFind|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
      ?>
      <? //if (!empty($urls) || $openUrl): ?>
      <!--<tr>
        <th><?//=$this->transEsc('Online Access')?>: </th>
        <td>
          <? //foreach ($urls as $current): ?>
            <a href="<?//=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?//=$this->escapeHtml($current['desc'])?></a><br/>
          <? //endforeach; ?>
          <? //if ($openUrl): ?>
            <?//=$this->openUrl($openUrl)?><br/>
          <? //endif; ?>
        </td>
      </tr>-->
      <? //endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <? if (count($tagList) > 0): ?>
                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
              <? else: ?>
                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
              <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>

    <?/* Display Additional Details */?>
    <table id="top-hidden" class="table table-striped">
      <? $this->MarcFields()->returnMarcData('top-hidden'); ?>
    </table>
    <?/* End Additional Details */?>
  </div><!--/.col-sm-9-->

  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
      <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>" class="modal-link"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?//=$this->record($this->driver)->getPreviews()?>
    <?=$this->record($this->driver)->getPreviewData()?>
  </div><!--/.col-sm-3-->
</div><!--/.row-->
