<? ### UChicago customization ### ?>
<!--<p><?//=$this->transEsc('choose_login_method')?></p>-->
<? ### ./UChicago customization ### ?>
<div id="authcontainer">
<?php $methods = $this->auth()->getManager()->getSelectableAuthOptions(); ?>
<?php $count = count($methods); ?>
<?php foreach ($methods as $loop => $method):?>
  <div class="authmethod<?=$loop?> span<?=floor(12 / $count) ?>">
    <?php $this->auth()->getManager()->setAuthMethod($method) ?>
    <? ### UChicago customization ### ?>
    <?//=$this->auth()->getLoginDesc() ?>
    <? ### ./UChicago customization ### ?>
    <?=$this->auth()->getLogin() ?>
  </div>
<?php endforeach ?>
</div>
<?php $this->auth()->getManager()->setAuthMethod('ChoiceAuth') ?>
