<form class="form-inline navbar-form navbar-left mini-search-form"  method="get" action="<?=$this->url('alphabrowse-home')?>" name="alphaBrowseForm" id="alphaBrowseForm">
  <label for="alphaBrowseForm_from"><?=$this->transEsc('starting from') ?></label>
  <span class="twitter-typhead"><input placeholder="a manual for writers of" class="form-control search-query autocomplete searcher:Solr tt-input" type="text" name="from" id="alphaBrowseForm_from" value="<?=$this->escapeHtml($this->from) ?>"/></span>
  <label class="offscreen"  for="alphaBrowseForm_source"><?=$this->transEsc('Browse Alphabetically') ?></label>
  <select id="alphaBrowseForm_source" name="source" class="form-control">
    <? foreach ($this->alphaBrowseTypes as $key => $item): ?>
      <option value="<?=$this->escapeHtml($key) ?>"<? if ($this->source == $key): ?> selected="selected"<? endif; ?>><?=$this->transEsc($item) ?></option>
    <? endforeach; ?>
  </select>
  <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('Browse') ?>"/>
</form>
