<? // Set default value if necessary:
   if (!isset($this->searchClassId)) {
       $this->searchClassId = 'Solr';
   }
    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $advSearch = $options->getAdvancedSearchAction();

    // Initial show or hide based on location ("home" = alphabrowse)
    $state = ($this->layout()->templateName == 'home' ? 'on' : 'off');
    
    // Due to my failure to access the search object parameters correctly here - brad
    $this->from = isset($_GET["from"]) ? $_GET["from"] : '';
    $this->source = isset($_GET["source"]) ? $_GET["source"] : '';
?>

<form class="form-inline navbar-form navbar-left mini-search mini-search-<?=$this->SearchContext()->getInitialSearchboxPref('browse', $this->templateDir, $this->templateName)?>"  method="get" action="<?=$this->url('alphabrowse-home')?>" name="alphaBrowseForm" id="alphaBrowseForm">
  <label for="alphaBrowseForm_from"><?=$this->transEsc('starting from') ?></label>
  <input class="form-control search-query autocomplete searcher:Solr" type="text" name="from" id="alphaBrowseForm_from" value="<?=$this->escapeHtml($this->from) ?>"/>
  <label for="alphaBrowseForm_source"><i class="fa fa-sort-alpha-asc"></i></label>
  <select id="alphaBrowseForm_source" name="source" class="form-control">
    <? foreach ($this->alphaBrowseTypes as $key => $item): ?>
      <option value="<?=$this->escapeHtml($key) ?>"<? if ($this->source == $key): ?> selected="selected"<? endif; ?>><?=$this->transEsc($item) ?></option>
    <? endforeach; ?>
  </select>
  <!--<input class="btn btn-primary" type="submit" value="<?=$this->transEsc('Browse') ?>"/>-->
  <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> <?=$this->transEsc("Browse")?></button>
  <a href="#" role="button" class="btn btn-link mini-box-toggle keyword"><?=$this->transEsc("Keyword")?></a> | <a href="<?=$this->url($advSearch)?>" role="button" class="btn btn-link mini-adv-link"><?=$this->transEsc("Advanced")?></a>
  |
  <a class="mini-worldcat-link btn btn-link" href="http://forms2.lib.uchicago.edu/lib/worldcatlookup/?<?php echo $_SERVER['QUERY_STRING']; ?>">Repeat search in WorldCat</a>
</form>
