<?
  $this->headTitle($this->translate('Browse the Collection Alphabetically'));
  //$this->layout()->breadcrumbs = '<a href="' . $this->url('alphabrowse-home') . '">' . $this->transEsc('Browse Alphabetically') . '</a>';
  //$this->layout()->searchbox= true;
  $baseQuery = array('source' => $this->source, 'from' => $this->from);
?>

<? /* LOAD THE LINK INFORMATION INTO $pageLinks, similar to smarty's {capture} */ ?>
<? ob_start(); ?>
  <ul class="pager-phoenix">
    <? if (isset($this->prevpage)): ?>
      <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => $baseQuery + array('page' => $this->prevpage))))?>">&laquo; <?=$this->transEsc('Prev')?></a>&nbsp;&nbsp;</li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>

    <? if (isset($this->nextpage)): ?>
      <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => $baseQuery + array('page' => $this->nextpage))))?>"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? $pageLinks = ob_get_contents(); ?>
<? ob_end_clean(); ?>

<? if ($this->result): ?>
  <div class="row">
  <div class="col-sm-12">
  <?=$pageLinks ?>
  <!-- end col-sm-12-->
  <!-- end row-->
  <div class="row">
  <div class="col-sm-12">
  <table class="alphabrowse table table-striped <?=$this->source . '-browse'?>">
    <thead>
      <tr>
        <th class="<?=$this->source ?>">
          <?=$this->transEsc("browse_" . $this->source) ?>
        </th>
        <? foreach ($this->extras as $e): ?>
          <th><?=$this->transEsc("browse_" . $e) ?></th>
        <? endforeach; ?>
        <th class="titles"><?=$this->transEsc("alphabrowse_matches") ?></th>
      </tr>
    </thead>
    <tbody>
      <? foreach ($this->result['Browse']['items'] as $item): ?>
        <tr>
          <td class="<?=$this->source ?>">
            <? if ($item['count'] > 0): ?>
              <?/* linking using bib ids is generally more reliable than
                doing searches for headings, but headings give shorter
                queries and don't look as strange. */?>
              <? if ($item['count'] < 5): ?>
                <? $query = array('type' => 'ids', 'lookfor' => implode(' ', $item['ids']), 'sort' => 'title'); ?>
              <? else: ?>
                <? $query = array('type' => ucwords($this->source) .  'Browse', 'lookfor' => '"' . addcslashes($item['heading'], '"') . '"', 'sort' => 'title'); ?>
              <? endif; ?>
              <a href="<?=$this->escapeHtmlAttr($this->url('search-results', array(), array('query' => $query)))?>"><?=$this->escapeHtml($item['heading'])?></a>
            <? else: ?>
              <?=$this->escapeHtml($item['heading'])?>
            <? endif; ?>

            <? if (count($item['useInstead']) > 0): ?>
              <div>
                <?=$this->transEsc('Use instead') ?>:
                <ul>
                  <? foreach ($item['useInstead'] as $heading): ?>
                  <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => array('from' => $heading) + $baseQuery)))?>"><?=$this->escapeHtml($heading)?></a></li>
                  <? endforeach; ?>
                </ul>
              </div>
            <? endif; ?>

            <? if (count($item['seeAlso']) > 0): ?>
              <div>
                <?=$this->transEsc('See also') ?>:
                <ul>
                  <? foreach ($item['seeAlso'] as $heading): ?>
                  <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => array('from' => $heading) + $baseQuery)))?>"><?=$this->escapeHtml($heading)?></a></li>
                  <? endforeach; ?>
                </ul>
              </div>
            <? endif; ?>

            <? if ($item['note']): ?>
              <div>
                <?=$this->transEsc('Note') ?>:
                <ul>
                  <li><?=$this->escapeHtml($item['note'])?></li>
                </ul>
              </div>
            <? endif; ?>
          </td>

          <? foreach ($this->extras as $extraName): ?>
            <td>
              <?
                $extraDisplayArray = array();
                foreach ($item['extras'][$extraName] as $j => $e):
                  $extraDisplayArray = array_unique(array_merge($extraDisplayArray, $e));
                endforeach;
                if (count($extraDisplayArray) > 1) {
                    switch ($extraName) {
                        case 'publishDate':
                            $extraDisplayArray = array('Multiple dates');
                            break;
                        case 'author':
                            $extraDisplayArray = array('Multiple authors');
                            break;
                    }
                }
                echo empty($extraDisplayArray) ? '&nbsp;' : implode('<br />', $extraDisplayArray);
              ?>
            </td>
          <? endforeach; ?>

          <td class="titles">
            <? if ($item['count'] > 0): ?>
               <a href="<?=$this->escapeHtmlAttr($this->url('search-results', array(), array('query' => $query)))?>"><?=$item['count']; ?></a>
            <? endif; ?>
          </td>
        </tr>
      <? endforeach; ?>
    </tbody>
  </table>
  <!-- end col-sm-12-->
  <!-- end row-->
  <div class="row">
  <div class="col-sm-12">
  <?= $pageLinks ?>
  <!-- end col-sm-12-->
  <!-- end row-->
<? endif; ?>
