<?
    // Set page title.
    $this->headTitle($this->translate('Export Favorites'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li><a href="' .$this->url('cart-home'). '">' .$this->transEsc('Cart'). '</a></li> '
    . '<li class="active">' . $this->transEsc('Export Favorites') . '</li>';
?>
<h2><?=$this->transEsc('Export Favorites')?></h2>

<?=$this->flashmessages()?>

<? if (!empty($this->exportOptions)): ?>
  <form class="form-cart-export form-horizontal" method="post" action="<?=$this->url('cart-export')?>" name="exportForm" title="<?=$this->transEsc('Export Items')?>">
    <? foreach ($this->records as $current): ?>
      <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($current->getSourceIdentifier() . '|' . $current->getUniqueId())?>" />
    <? endforeach; ?>
    <div class="form-group">
    <label for="format" class="control-label"><?=$this->transEsc('Format')?>:</label>
      <select name="format" id="format" class="form-control">
        <? $firstOption = null; ?>
        <? foreach ($this->exportOptions as $exportOption): ?>
          <? if ($firstOption == null) $firstOption = $exportOption; ?>
          <option value="<?=$this->escapeHtmlAttr($exportOption)?>"<? if($this->export()->needsRedirect($exportOption)): ?> data-redirect<? endif; ?>><?=$this->transEsc($this->export()->getLabelForFormat($exportOption))?></option>
        <? endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <input class="export btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Export')?>"<? if($this->export()->needsRedirect($firstOption)): ?> data-lightbox-ignore<? endif; ?>/>
    </div>
  </form>
<? endif; ?>
<?
  $script = <<<JS
  $('button.btn.hidden').removeClass('hidden');
  $('#itemhide').removeClass('in');
  $('.export.btn').click(function exportButtonClick() {
    if (typeof $('#format option:selected').attr('data-redirect') !== 'undefined') {
      VuFind.modal('hide');
    }
  });
  $('#format').change(function exportFormatChange(e) {
    if (this.selectedOptions[0].getAttribute('data-redirect') === null) {
      $('.export.btn').removeAttr('data-lightbox-ignore');
      $('form[name=exportForm]').removeAttr('target');
    } else {
      $('.export.btn').attr('data-lightbox-ignore', '1');
      $('form[name=exportForm]').attr('target', this.selectedOptions[0].value + 'Main');
    }
  }).trigger('change');
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
