<?
    // Set up page title:
    $this->headTitle($this->translate('Add a non-CNetID account to VuFind'));

    // Set up breadcrumbs:
    /*$this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('Account') . '</em>';*/

    // Set the searchbox based on user preference (past action for now)
    //$this->render('/search/user-search-preferences.phtml');
?>

<div class="span10">
<h2>Add a non-CNetID account to VuFind</h2>
<?=$this->flashmessages()?>

<? if (!$this->success): ?>
	<form method="post" action="" name="accountForm" id="accountForm">
	<label class="span-3" for="account_username">Barcode:</label>
	<input id="account_barcode" type="text" name="barcode" value="<?=$this->escapeHtml($this->barcode)?>" size="30" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
	<br class="clear"/>
	<label class="span-3" for="account_lastname">Last Name:</label>
	<input id="account_lastname" type="text" name="lastname" value="<?=$this->escapeHtml($this->lastname)?>" size="30" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
	<br class="clear"/>
	<label class="span-3" for="account_pin">PIN:</label>
	<input id="account_pin" type="password" autocomplete="off" name="pin1" value="" size="30" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
	<br class="clear"/>
	<label class="span-3" for="account_pin">PIN (repeat):</label>
	<input id="account_pin" type="password" autocomplete="off" name="pin2" value="" size="30" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
	<br class="clear"/>
	<input class="push-3 button" type="submit" name="submit" value="Add this account to VuFind"/>
	</form>
<? else: ?>
    <p><a href="/vufind/Admin/Pin">Return to accounts view.</a></p>
<? endif; ?>

</div>
<br class="clear"/>
