<?
    // Set up page title:
    $this->headTitle($this->translate('Delete user'));

    // Set up breadcrumbs:
    /*$this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('Account') . '</em>';*/

    // Set the searchbox based on user preference (past action for now)
    //$this->render('/search/user-search-preferences.phtml');
?>

<div class="span10">
<h2>Delete an account from VuFind</h2>
<?=$this->flashmessages()?>

<? if ($this->barcode): ?>
<form method="post" action="" name="deletePinForm" id="deletePinForm">
<label class="span-3" for="account_username">Barcode:</label>
<?=$this->escapeHtml($this->barcode)?>
<br class="clear"/>

<label class="span-3" for="account_lastname">First Name:</label>
<?=$this->escapeHtml($this->firstname)?>
<br class="clear"/>

<label class="span-3" for="account_lastname">Last Name:</label>
<?=$this->escapeHtml($this->lastname)?>
<br class="clear"/>

<input class="push-3 button" type="submit" name="submit" value="Delete this account from VuFind"/>
</form>
<? else: ?>
<p><a href="/vufind/Admin/Pin">Return to accounts view.</a></p>
<? endif; ?>

</div>
<br class="clear"/>
