<?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
  <div class="bulkActionButtons hidden-print">
    <div class="bulk-checkbox">
      <label>
        <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/>
        <span>Select records #<?=$this->localizedNumber($this->results->getStartRecord())?>-<?=$this->localizedNumber($this->results->getEndRecord())?>:
        </span>
      </label>
    </div>
    <div class="btn-group">
      <?php if (isset($this->showBulkOptions) && $this->showBulkOptions): ?>
        <input id="ribbon-email" class="btn btn-link" data-lightbox type="submit" name="email" title="<?=$this->transEsc('bookbag_email_selected')?>" value="<?=$this->transEsc('Email')?>"<?if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
        <?php $exportOptions = $this->export()->getBulkOptions(); if (count($exportOptions) > 0): ?>
          <input id="ribbon-export" class="btn btn-link" data-lightbox type="submit" name="export" title="<?=$this->transEsc('bookbag_export_selected')?>" value="<?=$this->transEsc('Export')?>" <?if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
        <?php endif; ?>
        <input id="ribbon-print" class="btn btn-link" data-lightbox type="submit" name="print" title="<?=$this->transEsc('bookbag_print_selected')?>" value="<?=$this->transEsc('Print')?>" <?if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
        <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
          <input id="ribbon-save" class="btn btn-link" data-lightbox type="submit" name="saveCart" title="<?=$this->transEsc('bookbag_save_selected')?>" value="<?=$this->transEsc('Save')?>" <?if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($this->showCartControls) && $this->showCartControls): ?>
        <input id="<?=$this->idPrefix?>updateCart" type="submit" class="btn btn-link" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
