<?php if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<?php $i = $this->indexStart; ?>
<?php foreach ($this->results->getResults() as $current): ?>
  <?php $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="result<?=$current->supportsAjaxStatus()?' ajaxItem':''?>">
    <div class="checkbox hidden-print col-xs-1">
      <?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
        <label class="hidden-xs hidden-sm">
      <?=$this->record($current)->getCheckbox('', 'search-cart-form', $recordNumber)?>
        </label>
      <?php else: ?>
        <span class="hidden-xs hidden-sm"><?=$recordNumber ?></span>
      <?php endif; ?>
    </div>
    <?=$this->record($current)->getSearchResult('list')?>
  </div>
<?php endforeach; ?>
