<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>
<? // Display a message if the form has been submitted ?>
<? if ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
    <? 
    $style = 'margin-bottom:-6px; font-size:15px;'; 
    if ($this->failure) { 
        $msg = 'Some of your items failed to renew!<br/>Please talk with a librarian or '  
             . '<a href="http://www.lib.uchicago.edu/e/using/borrow/">counsult our '
             . 'borrowing policies page</a> if you have any questions.';
        echo $this->BootstrapAlert()->makeAlert('danger', $msg, $style);
    }
    else {
        $msg= 'Success! All of your items successfully renewed! ';
        echo $this->BootstrapAlert()->makeAlert('success', $msg, $style);
    }
    ?>
<? endif; ?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><? printf("%s <small>(%d)</small>", $this->transEsc('Checked Out Items'), count($this->transactions)); ?></h2>
    <?=$this->flashmessages()?>

    <? if (!empty($this->transactions)): ?>
      <? if ($this->renewForm): ?>
        <p style="margin-bottom: 0; margin: -10px 0 15px 0;">Need to renew books?
          <a href="http://www.lib.uchicago.edu/e/using/borrow/#contact">Call us</a> or use our 
          <a href="http://www.lib.uchicago.edu/e/ask/contactcirc.html">online form</a> and Library staff will help you.
        </p>

      <form name="renewals" action="<?=$this->url('myresearch-home')?>" method="post" id="renewals">
        <div class="toolbar">
          <input type="submit" class="btn btn-default" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
          <input type="submit" class="btn btn-default" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
        </div>
      <? endif; ?>

      <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Renewal Count</th>
          <th>Title</th>
          <th>Call Number</th>
          <th>Barcode</th>
          <th>Checked Out</th>
          <th>Due Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <? $i = 0; foreach ($this->transactions as $resource): ?>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <tr>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row">
          <td>
          <? if ($this->renewForm): ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
              <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
              <input class="pull-left" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
              <input class="pull-left" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
            <? endif; ?>
          <? endif; ?>
          </td>
          <td>
            <?=$ilsDetails['renew']?>
          </td> 
          <td>
            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                <? $renewalStatus = $this->renewResult[$ilsDetails['item_id']]['success']?>
                <? if ($renewalStatus): ?>
                    <strong class="text-success">Successfully renewed!</strong>
                <? else: ?>
                    <strong class="text-danger"><?=$this->renewResult[$ilsDetails["item_id"]]["sysMessage"]?></strong><br/>
                <? endif; ?>
            <? endif; ?>
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }

              $titleDetails = '';
              if (isset($ilsDetails['copy']) && !empty($ilsDetails['copy'])) {
                  $titleDetails .= $ilsDetails['copy'];
              }
              if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])) {
                  $titleDetails .= ' ' . $ilsDetails['volume'];
              }
              if ($titleDetails != '') {
                  echo '<br/>' . $titleDetails;
              }
            ?><br/>
            <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
              <?=$this->transEsc('by')?>:
              <?=$this->escapeHtml($listAuthor)?><br/>
            <? endif; ?>
            <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
              <?=$this->record($resource)->getFormatList()?>
              <br/>
            <? endif; ?>

            <? if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], array(), $ilsDetails['institution_name'])?></strong>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], array(), $ilsDetails['borrowingLocation'])?>
              <br />
            <? endif; ?>
          </td>

          <td>
            <?php print $ilsDetails['callNumber']; ?>
          </td>

          <td>
            <? if (isset($ilsDetails['barcode']) && !empty($ilsDetails['barcode'])): ?>
              <div><?=$this->escapeHtml($ilsDetails['barcode'])?></div>
            <? endif; ?>
          </td>

          <td>
            <? if (isset($ilsDetails['loanedDate']) && !empty($ilsDetails['loanedDate'])): ?>
              <div><?=$this->escapeHtml($ilsDetails['loanedDate'])?></div>
            <? endif; ?>
          </td>

          <td>
            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                <?=$this->escapeHtml($renewDetails['new_date'])?> <? if (isset($renewDetails['new_time']) && $ilsDetails['dueTime']): ?><?=date("g:ia", strtotime($renewDetails['new_time']))?><? endif; ?>
            <? elseif ($ilsDetails['duedate'] === null): ?>
                no due date unless recalled
            <? else: ?>
              <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime']) && $ilsDetails['dueTime'] != '00:00:00.0'): ?> <?=date("g:ia", strtotime($ilsDetails['dueTime']))?><? endif; ?>
            <? endif; ?>
          </td>

          <td>
            <? if (false): // supress renewable column ?>
            <? $showStatus = true; ?>
            <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <? endif; ?>
            <? endif; // end supress renewable column ?>
          </td>
        </div>
        </tr>
      <? endforeach; ?>
      </tbody>
      </table>
      <? if ($this->renewForm): ?></form><? endif; ?>
    <? else: ?>
      <?=$this->transEsc('You do not have any items checked out')?>.
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
  </div>
</div>
