<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Checked Out Items')?> <small>(<?=count($this->transactions)?>)</small></h2>

    <?=$this->flashmessages()?>
    <? if ($this->itemsOverdue) : ?>
        <?=$this->BootstrapAlert()->makeAlert('danger', 'You have item(s) overdue.', ''); ?>
    <? endif; ?>
    <? if ($this->itemsDueSoon): ?>
        <?=$this->BootstrapAlert()->makeAlert('warning', 'You have item(s) due soon.', ''); ?>
    <? endif; ?>
    <? $warnMsg = 'Please do not click renew twice-renewals can take up to a minute.<br/>For help, <a href="https://www.lib.uchicago.edu/about/directory/?view=department&query=circulation" target="_blank" class="external">Call us</a> or use our <a href="https://www.lib.uchicago.edu/borrow/borrowing/contact-circulation/" target="_blank" class="external">online form</a> and Library staff will help you.'; ?>
    <?=$this->BootstrapAlert()->makeAlert('warning', $warnMsg, ''); ?>
    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <? if (!empty($this->transactions)): ?>
      <? if ($this->renewForm): ?>
      <form name="renewals" method="post" id="renewals">
        <input id="checked_out_items_sort_field" type="hidden" name="sort" value="<?=$this->sort; ?>"/>
        <div class="toolbar">
          <div class="checkbox">
             <label>
               <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/>
               <span>Select all</span>
             </label>
            <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
            <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
          </div>
        </div>
      <? endif; ?>

      <? if ($paginator): ?>
        <?=$this->transEsc("Showing")?>
        <? $start = $paginator->getAbsoluteItemNumber(1);
           $end = $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage());
           $total = $paginator->getTotalItemCount();
        ?>
        <strong><?=$this->localizedNumber($start)?></strong> - <strong><?=$this->localizedNumber($end > $total ? $total : $end)?></strong>
        <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($total)?></strong>
      <? endif; ?>

      <? foreach ($hiddenTransactions as $ilsDetails): ?>
        <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
          <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
          <? $prefix = isset($ilsDetails['title']) ? $ilsDetails['title'] : $ilsDetails['item_id']; ?>
          <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
            <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
          <? else: ?>
            <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
          <? endif; ?>
        <? endif; ?>
        <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
          <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <? endif; ?>
      <? endforeach; ?>

      <? $i = 0; foreach ($this->transactions as $resource): ?>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row result">
          <? if ($this->renewForm): ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
              <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
              <div class="col-xs-1">
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" data-record-id="<?=$this->escapeHtmlAttr($resource->getSourceIdentifier() . '|' . $resource->getUniqueId());?>"/>
                <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
                <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              </div>
            <? endif; ?>
          <? endif; ?>

          <? $cover = $this->record($resource)->getCover('checkedout', 'medium'); ?>
          <? if ($cover): ?>
            <div class="col-sm-2 hidden-xs text-center">
            <? /* Display thumbnail if appropriate: */ ?>
              <?=$cover?>
            </div>
         <? endif; ?>
         <div class="col-xs-12 col-sm-9">
         <div class="row">
         <div class="col-sm-6 col-xs-12">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <?
              $locationName = $ilsDetails['locationName'];
              if ($locationName) {
                echo $locationName . "<br/>";
              }
            ?>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], [], $ilsDetails['institution_name'])?></strong>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], [], $ilsDetails['borrowingLocation'])?>
              <br />
            <? endif; ?>
 
            <? $showStatus = false; ?>

            <? /* UChicago custom code */ ?>
            <? $duedate = $ilsDetails['duedate']; ?>
            <? if (!$duedate) :?>
                <? $duedate = 'no due date unless recalled.'; ?>
            <? endif; ?>

            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
              <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <? $showStatus = false; ?>
                <strong class="due-date"><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($renewDetails['new_date'])?> <? if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><? endif; ?></strong>
              <? else: ?>
                <strong class="due-date"><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($duedate)?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
              <? endif; ?>
            <? else: ?>
              <strong class="due-date"><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($duedate)?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
            <? endif; ?>

            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <? endif; ?>
          </div><? /* end col */ ?>
          <div class="col-sm-6 col-xs-12">
            <? $callNumber = $ilsDetails['callNumber']; ?>
            <? if ($callNumber) : ?>
                <?=$callNumber?><br/>
            <? endif; ?>

            <? $barcode = $ilsDetails['barcode']; ?>
            <? if ($barcode) : ?>
                 <strong>Barcode: </strong> <?=$barcode?><br/>
            <? endif; ?>

           <? if (isset($ilsDetails['renew'])): ?>
              <strong><?=$this->transEsc('Renewal Count')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
              <? if (isset($ilsDetails['renewLimit'])): ?>
                / <?=$this->transEsc($ilsDetails['renewLimit'])?>
              <? endif; ?>
              <br />
            <? endif; ?>

            <? $loanedDate = $ilsDetails['loanedDate']; ?>
            <? if ($loanedDate) : ?>
                <strong>Checked Out: </strong> <?=$loanedDate?><br/>
            <? endif; ?> 
          </div><? /* end col */ ?>

            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
             <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
             <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <? $showStatus = false; ?>
                <div class="col-xs-12 col-sm-10 alert alert-success"><?=$this->transEsc('renew_success')?></div>
              <? else: ?>
                <div class="col-xs-12 col-sm-10 alert alert-danger"><?=$this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
              <? endif; ?>
           <? endif; ?>

          <? if ($showStatus): ?>
            <? if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
              <div class="col-xs-12 col-sm-10 alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
            <? elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
              <div class="col-xs-12 col-sm-10 alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
            <? endif; ?>
          <? endif; ?>

          <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
            <div class="col-xs-12 col-sm-10 alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
          <? endif; ?>

          <? /* UChicago custom code */ ?>
          <? if ($ilsDetails['overdue']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-danger">Overdue </div>
          <? elseif ($ilsDetails['duesoon']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-warning">Due Soon </div>
          <? endif; ?>

          </div><? /* end row */ ?>
          </div>
        </div>
      <? endforeach; ?>
      <? if ($this->renewForm): ?></form><? endif; ?>
      <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
    <? else: ?>
      <?=$this->transEsc('You do not have any items checked out')?>.
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
  </div>
</div>
