<?php
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

    // Check if "Renew All" button can be displayed:
    $renewAll = !$this->ilsPaging || !$paginator;

    // UChicago customization
    // Since the OLE api returns incomplete data, we must create a test for "patron level"
    // renewal failures and capture the data for display purposes. This wouldn't be needed
    // if the OLE api returned something that made sense in these cases.
    $patronFail = false;
    if (isset($this->renewResult) && count($this->renewResult)) {
        $isMissingBarcode = array_key_exists('', $this->renewResult);
        if($isMissingBarcode && $this->renewResult['']['success'] == false && $this->renewResult['']['new_date'] == '' && $this->renewResult['']['item_id'] == '' && $this->renewResult['']['code'] == '' ) {
            $patronFail = true;
            $patronFailMsg = $this->renewResult['']['sysMessage'];
        }
    }
?>
<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?> col-sm-9">
    <h2><?=$this->transEsc('Checked Out Items')?> <small>(<?=count($this->transactions)?>)</small></h2>

    <?=$this->flashmessages()?>
    <?php if (isset($_POST['renewSelected']) || isset($_POST['renewAll'])): ?>
        <?php if ($failure): ?>
            <?=$this->BootstrapAlert()->makeAlert('danger', 'Some items could not be renewed. Please see below.', ''); ?>
        <?php else: ?>
            <?=$this->BootstrapAlert()->makeAlert('success', 'Success! All of your items renewed.', ''); ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->itemsOverdue) : ?>
        <?=$this->BootstrapAlert()->makeAlert('danger', 'You have item(s) overdue.', ''); ?>
    <?php endif; ?>
    <?php if ($this->isLost) : ?>
        <?=$this->BootstrapAlert()->makeAlert('danger', 'You have item(s) billed as lost.', ''); ?>
    <?php endif; ?>
    <?php if ($this->recalled) : ?>
        <?=$this->BootstrapAlert()->makeAlert('danger', 'You have item(s) recalled.', ''); ?>
    <?php endif; ?>
    <?php if ($this->itemsDueSoon): ?>
        <?=$this->BootstrapAlert()->makeAlert('warning', 'You have item(s) due soon.', ''); ?>
    <?php endif; ?>
    <?php if ($this->claimsReturned): ?>
        <?=$this->BootstrapAlert()->makeAlert('info', 'You have item(s) claimed as returned.', ''); ?>
    <?php endif; ?>
    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <?php if (!empty($this->transactions)): ?>
      <?php if ($this->renewForm): ?>
      <?php $disabled = ''; ?>
      <?php if (isset($_POST['renewSelected']) || isset($_POST['renewAll'])): ?>
        <?php $disabled = 'disabled'; ?>
      <?php endif; ?>
      <form name="renewals" method="post" id="renewals">
        <input id="checked_out_items_sort_field" type="hidden" name="sort" value="<?=$this->sort; ?>"/>
        <div class="toolbar">
          <div class="checkbox">
             <!--<label>
               <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/>
               <span>Select all</span>
             </label>-->
             <?php if ($renewAll): ?>
               <input type="submit" class="btn btn-primary" id="renewAll" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
             <?php endif; ?>
            <input type="submit" class="btn btn-default <?=$disabled?>" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
          </div>
        </div>
      <?php endif; ?>

    <nav class="search-header hidden-print">
      <?php if ($paginator): ?>
        <div class="search-stats">
          <?php
            $end = min(
              $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage()),
              $paginator->getTotalItemCount()
            );
            $transParams = [
              '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
              '%%end%%' => $this->localizedNumber($end),
              '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount())
            ];
          ?>
          <?=$this->translate('showing_items_of_html', $transParams); ?>
        </div>
      <?php endif; ?>
      <?php if ($this->sortList): ?>
        <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
      <?php endif; ?>
    </nav>

      <?php foreach ($hiddenTransactions as $ilsDetails): ?>
        <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
          <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
        <?php $prefix = $ilsDetails['title'] ?? $ilsDetails['item_id']; ?>
          <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
            <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
          <?php else: ?>
            <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></div>
          <?php endif; ?>
        <?php endif; ?>
        <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
          <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
          <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <?php endif; ?>
      <?php endforeach; ?>

      <?php $i = 0; foreach ($this->transactions as $resource): ?>
        <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row result">
          <?php if ($this->renewForm): ?>
            <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
              <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
              <div class="col-xs-1">
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" data-record-id="<?=$this->escapeHtmlAttr($resource->getSourceIdentifier() . '|' . $resource->getUniqueId());?>"/>
                <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
                <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              </div>
            <?php endif; ?>
          <?php endif; ?>

          <?php $cover = $this->record($resource)->getCover('checkedout', 'medium'); ?>
          <?php if ($cover): ?>
            <div class="col-sm-2 hidden-xs text-center">
            <?php /* Display thumbnail if appropriate: */ ?>
              <?=$cover?>
            </div>
         <?php endif; ?>
         <div class="col-xs-12 col-sm-9">
         <div class="row">
         <div class="col-sm-6 col-xs-12">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title">' . $title . '</a>';
              } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <?php $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><?php if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?><br/>
            <?php endif; ?>
            <?php $locationName = $ilsDetails['locationName']; ?>
            <?php if ($locationName): ?>
                <?=$locationName ?><br/>
            <?php endif; ?>
            <?php if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <?php endif; ?>

            <?php if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <?php endif; ?>

            <?php if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], [], $ilsDetails['institution_name'])?></strong>
              <br />
            <?php endif; ?>

            <?php if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], [], $ilsDetails['borrowingLocation'])?>
              <br />
            <?php endif; ?>
 
            <?php $showStatus = false; ?>

            <?php /* UChicago custom code */ ?>
            <?php $duedate = $ilsDetails['duedate']; ?>
            <?php if (!$duedate) :?>
                <?php $duedate = 'no due date unless recalled.'; ?>
            <?php endif; ?>

            <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
              <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <?php $showStatus = false; ?>
                <strong class="due-date"><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($renewDetails['new_date'])?> <?php if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><?php endif; ?></strong>
              <?php else: ?>
                <strong class="due-date"><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($duedate)?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?></strong>
              <?php endif; ?>
            <?php else: ?>
              <strong class="due-date"><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($duedate)?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?></strong>
            <?php endif; ?>

            <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <?php endif; ?>
          </div><?php /* end col */ ?>
          <div class="col-sm-6 col-xs-12">
            <?php $callNumber = $ilsDetails['callNumber']; ?>
            <?php if ($callNumber) : ?>
                Call Number: <strong><?=$callNumber?></strong><br/>
            <?php endif; ?>

            <?php $barcode = $ilsDetails['barcode']; ?>
            <?php if ($barcode) : ?>
                 Barcode: <strong> <?=$barcode?></strong><br/>
            <?php endif; ?>

           <?php if (isset($ilsDetails['renew'])): ?>
              <?=$this->transEsc('Renewal Count')?>:<strong> <?=$this->transEsc($ilsDetails['renew'])?></strong>
              <?php if (isset($ilsDetails['renewLimit'])): ?>
                / <?=$this->transEsc($ilsDetails['renewLimit'])?>
              <?php endif; ?>
              <br />
            <?php endif; ?>

            <?php $loanedDate = $ilsDetails['loanedDate']; ?>
            <?php if ($loanedDate) : ?>
                Checked Out: <strong> <?=$loanedDate?></strong><br/>
            <?php endif; ?>
 
            <?php if ($ilsDetails['proxyBorrower']): ?>
              Checked Out By: <strong> <?=$ilsDetails['proxyBorrower']; ?></strong><br/>
            <?php endif; ?>

            <?php /* UChicago custom code */ ?>
            <?php $loanTypeCode = $ilsDetails['loanTypeCode']; ?>
            <?php $loanTypeLabel = $ilsDetails['loanType']; ?>
            <?php if ($loanTypeCode != 'stks' && !empty($loanTypeLabel)) :?>
                <?php if ($loanTypeLabel != 'ZZZ'):?>
                    <span class="item-type"><?=$loanTypeLabel?></span><br/>
                <?php endif; ?>
            <?php endif; ?>
          </div><?php /* end col */ ?>

            <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
             <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
             <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <?php $showStatus = false; ?>
                <div class="col-xs-12 col-sm-10 alert alert-success"><?=$this->transEsc('renew_success')?></div>
              <?php else: ?>
                <div class="col-xs-12 col-sm-10 alert alert-danger"><?=$this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$renewDetails['sysMessage']?><?php endif; ?></div>
              <?php endif; ?>
           <?php endif; ?>

          <?php if ($showStatus): ?>
            <?php if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
              <div class="col-xs-12 col-sm-10 alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
            <?php elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
              <div class="col-xs-12 col-sm-10 alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
            <?php endif; ?>
          <?php endif; ?>

          <?php if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
            <div class="col-xs-12 col-sm-10 alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
          <?php endif; ?>

          <?php /* UChicago custom code */ ?>
          <?php if ($ilsDetails['overdue']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-danger">Overdue </div>
          <?php endif; ?>
          <?php if ($ilsDetails['isLost']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-danger">Billed as Lost</div>
          <?php endif; ?>
          <?php if ($patronFail): ?>
            <div class="col-xs-12 col-sm-10 alert alert-danger"><?=$patronFailMsg?></div>
          <?php endif; ?>
          <?php if ($ilsDetails['recalled']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-danger">Recalled</div>
          <?php endif; ?>
          <?php if (!$ilsDetails['overdue'] && !$ilsDetails['isLost'] && $ilsDetails['duesoon']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-warning">Due Soon </div>
          <?php endif; ?>
          <?php if ($ilsDetails['claimsReturned']): ?>
            <div class="col-xs-12 col-sm-10 alert alert-info">Claimed as returned</div>
          <?php endif; ?>
          </div><?php /* end row */ ?>
          </div>
        </div>
      <?php endforeach; ?>
      <?php if ($this->renewForm): ?></form><?php endif; ?>
      <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', compact('params')) : ''?>
    <?php else: ?>
      <?=$this->transEsc('You do not have any items checked out')?>.
    <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?> col-sm-3" id="myresearch-sidebar">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
  </div>
</div>
