<?
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <?=$this->flashmessages()?>

  <?php $badLevel = 0; ?>
  <?php foreach ($this->fines as $fail): ?>
    <?php if ($fail['balance'] > 0): ?>
       <?php $badLevel += $fail['balance']; ?>
       <?php if ($badLevel / 100 >= 50): ?>
          <div class="alert alert-danger" role="alert">
            Your account has an outstanding balance of $50 or more. As a result, your borrowing and renewing privileges have been temporarily suspended.
          </div>
          <?php break; ?>
       <?php endif; ?>
    <?php endif; ?>
  <?php endforeach; ?>

  <div class="alert alert-info" role="alert">
    See <a href="https://www.lib.uchicago.edu/borrow/borrowing/fines-and-lost-items/" target="_blank" class="external">Fines &amp; Lost Items</a> for payment options and other information. 
  </div>

<?
    // Get sort labels.
    $sort_labels = [
        'title' => 'Title',
        'billdate' => 'Bill Date',
        'checkout' => 'Date Checked Out',
        'duedate' => 'Due Date',
        'fine' => 'Fee Type',
        'amount' => 'Fine Amount'
    ];

    $sort = 'title';
?>

  <div class="toolbar">
    <form action="/vufind/Cart/Export" method="POST" style="display: inline;">
      <?php /* <input class="btn btn-default" name="export" value="Export as CSV" type="submit"> */ ?>
      <?php foreach ($this->fines as $record): ?>
        <input type="hidden" name="ids[]" value="<?=$record['id']?>"/>
      <?php endforeach; ?>
    </form>
    <span class="dropdown">
      <a href="#" onclick="window.print();return false;"><button class="btn btn-default" type="button">Print</button></a>
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort By: <strong id="fines_sort_label"><?=$sort_labels[$sort] ?></strong> <span class="caret"></span></button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li><a href="/vufind/MyResearch/Fines?sort=title">Title</a></li>
        <li><a href="/vufind/MyResearch/Fines?sort=billdate">Bill Date</a></li>
        <li><a href="/vufind/MyResearch/Fines?sort=checkout">Date Checked Out</a></li>
        <li><a href="/vufind/MyResearch/Fines?sort=duedate">Due Date</a></li>
        <li><a href="/vufind/MyResearch/Fines?sort=fine">Fee Type</a></li>
        <li><a href="/vufind/MyResearch/Fines?sort=amount">Fine Amount</a></li>
      </ul>
    </span>
  </div>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <?php if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <?php else: ?>
    <table class="table table-striped" summary="<?=$this->transEsc('Your Fines')?>">
    <thead>
    <tr>
      <th>Title &amp; Location</th>
      <th>Due date</th>
      <th>Return Date</th>
      <th>Bill Date</th>
      <th>Fee Type</th>
      <th>Fine Amount</th>
      <th>Balance</th>
    </tr>
    </thead>
    <?php $totalDue = 0; ?>
    <?php foreach ($this->fines as $record): ?>
      <?php if ($record['balance'] > 0): ?>
      <tr>
        <td>
          <?php if (empty($record['title'])): ?>
            <?=$this->transEsc('not_applicable')?>
          <?php elseif (!isset($record['driver']) || !is_object($record['driver'])): ?>
            <?php 
              $title = $this->escapeHtml(trim($record['title'], '/:'));
              if (isset($record['id'])) {
                echo '<a href="/vufind/Record/' . $record['id'] . '">' . $title . '</a>';
              } else {
                echo $title;
              }
            ?>
          <?php else: ?>
            <a href="<?=$this->recordLink()->getUrl($record['driver'])?>"><?=$this->escapeHtml(trim($record['title'], '/:'))?></a>
          <?php endif; ?>
          <?php
            $locationName = null;
            if (isset($record['locationName'])) {
              $locationName = $record['locationName'];
            }
            if (isset($locationName)) {
              echo "<br/>" . $locationName;
            }
          ?>
        </td>
        <td><?=isset($record['duedate']) ? $this->escapeHtml($record['duedate']) : ''?></td>
        <td><?=isset($record['returndate']) ? $this->escapeHtml($record['returndate']) : ''?></td>
        <td><?=isset($record['fine']) ?  $this->escapeHtml($record['billdate']) : ''?></td>
        <td><?=isset($record['fine']) ?  $this->escapeHtml($record['fine']) : ''?></td>
        <td><?=isset($record['amount']) ? $this->safeMoneyFormat($record['amount'] / 100.00) : ''?></td>
        <?php if (isset($record['suspended']) && $record['suspended']): ?>
          <td><?=isset($record['balance']) ? $this->escapeHtml('Suspended') : ''?></td>
        <?php else: ?>
          <td><?=isset($record['balance']) ? $this->safeMoneyFormat($record['balance']/100.00) : ''?></td>
        <?php endif; ?>
      </tr>
      <?php endif; ?>
      <?php if (!isset($record['suspended']) /*&& !$record['suspended'] - broke post 5.0 merge - brad */): ?>
        <?php $totalDue += $record['balance']; ?>
      <?php endif; ?>
    <?php endforeach; ?>
      <tr style="font-weight:bold"><td colspan="6"><?=$this->transEsc('Total Balance Due: ')?></td><td><?=$this->safeMoneyFormat($totalDue / 100.00) ?></td></tr>
    </table>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'fines'])?>
</div>
