<?php
  // Set up page title:
  $this->headTitle($this->translate('Requested Items'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?> col-sm-9">
    <h2><?=$this->transEsc('Requested Items') ?></h2>
    <?=$this->flashmessages()?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <?php if (!empty($this->recordList)): ?>
      <ul>
        <li>Requested items listed below are not yet available.</li>
        <li>When items are available for pickup, you will receive an email notification, including a link to reserve a time to pick up materials from the outer lobby of Regenstein.</li>
        <li>Items available for pickup will appear on your list of Checked Out Items.</li>
      </ul>
      <form>
        <div class="toolbar">
          <?
            $hold_labels = [
              'title' => 'Title',
              'author' => 'Author',
              'callNumber' => 'Call Number',
              'itemStatus' => 'Item Status',
              'holdExpirationDate' => 'On Hold Until Date'
            ];
          ?>
          <span class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Sort By: <strong><?=$hold_labels[$this->sort]?></strong> <span class="caret"></span></button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><a href="/vufind/MyResearch/Holds?sort=title">Title</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=author">Author</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=callNumber">Call Number</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=itemStatus">Item Status</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=holdExpirationDate">On Hold Until Date</a></li>
            </ul>
          </span>
        </div>
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>

    <?php $iteration = 0; ?>
    <?php foreach ($this->recordList as $resource): ?>
      <?php $iteration++; ?>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="result">
        <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
          <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
          <div class="checkbox">
            <label>
              <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" data-record-id="<?=$this->escapeHtmlAttr($resource->getSourceIdentifier() . '|' . $resource->getUniqueId());?>" />
            </label>
          </div>
        <?php endif; ?>

        <?php
          $coverDetails = $this->record($resource)->getCoverDetails('holds', 'small', $this->recordLink()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <?php $thumbnail = ob_get_contents(); ?>
          <?php ob_end_clean(); ?>
        <?php endif; ?>
        <div class="media">
          <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
          <div class="media-body">
            <?php
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                  . '" class="title">' . $title . '</a>';
              } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo '<span class="title">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <?php $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><?php if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?><br/>
            <?php endif; ?>

            <?php if (count($resource->getFormats()) > 0): ?>
              <?=$this->record($resource)->getFormatList() ?>
            <?php endif; ?>

            <?php if (isset($ilsDetails['available']) && $ilsDetails['available'] == true && (!(isset($ilsDetails['position']) && $ilsDetails['position'] > 1))): ?>
              <div class="text-success"><strong>Item Status:</strong> <?=$this->transEsc("hold_available") ?></div>
            <?php else: ?>
              <div class="text-danger"><strong>Item Status:</strong> Not Yet Available</div>
            <?php endif; ?>

            <?php if (isset($ilsDetails['volume']) && !empty(trim($ilsDetails['volume']))): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <?php endif; ?>

            <?php if (!empty($ilsDetails['shelvingLocation'])): ?>
              <?=$this->escapeHtml($ilsDetails['shelvingLocation'])?>
              <br />
            <?php endif; ?>

            <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <?php $pickupDisplay = ''; ?>
            <?php $pickupTranslate = false; ?>
            <?php if (isset($ilsDetails['location'])): ?>
              <?php if ($this->pickup): ?>
                <?php foreach ($this->pickup as $library): ?>
                  <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                    <?php $pickupDisplay = $library['locationDisplay']; ?>
                    <?php $pickupTranslate = true; ?>
                  <?php endif; ?>
                <?php endforeach; ?>
              <?php endif; ?>
              <?php if (empty($pickupDisplay)): ?>
                <?php $pickupDisplay = $ilsDetails['location']; ?>
              <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($pickupDisplay)): ?>
              <?=$this->transEsc('pick_up_location') ?>:
              <strong><?=$pickupTranslate ? $this->transEsc('location_' . $pickupDisplay, null, $pickupDisplay) : $this->escapeHtml($pickupDisplay)?></strong>
              <br />
            <?php endif; ?>

            <div><?=$this->transEsc("hold_queue_position") ?>: <?=$this->escapeHtml($ilsDetails['position']) ?></div>

            </div>
            <div class="media-body">
            <?php $callNumbers = $resource->getCallNumbers(); ?>
            <?php if (!empty($callNumbers)): ?>
                <?=$this->transEsc('Call Number') ?>:
                <strong><?=$callNumbers[0]; ?></strong><br/>
            <?php endif; ?>
            <?php if ($ilsDetails['item_id']): ?>
                Barcode: <strong><?=$ilsDetails['item_id']?></strong><br/>
            <?php endif; ?>

            <?php if (!empty($ilsDetails['expire']) && $ilsDetails['status'] != 'ONHOLD'): ?>
              <strong>Request expires:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?><br/>
            <?php //elseif (!empty($ilsDetails['hold_until_date'])): ?>
               <?php // Commented out for COVID-19 ?>
               <!--<strong>On Hold Until:</strong> <?//=$this->escapeHtml($ilsDetails['hold_until_date']) ?><br/>-->
            <?php endif; ?>

            <?php if (!empty($ilsDetails['loan_type'])): ?>
              <span class="item-type"><?=$this->escapeHtml($ilsDetails['loan_type'])?></span>
              <br />
            <?php endif; ?>
          </div>
          <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
        </div>
        <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" title="'.$this->escapeHtmlAttr($resource->getCoinsOpenUrl()).'"></span>':''?>
      </div>
    <?php endforeach; ?>
    <?php if ($this->cancelForm): ?></form><?php endif; ?>
  <?php else: ?>
    <ul>
      <li><?=$this->transEsc('You have no outstanding requests') ?>.</li>
      <li>Items available for pickup will appear on your list of Checked Out Items.</li>
      <li>If you have items awaiting pickup, check your email for an email notification, including a link to reserve a time to pick up materials from the outer lobby of Regenstein.</li>
    </ul>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?> col-sm-3" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holds'])?>
</div>
</div>
