<?
  // Set up page title:
  $this->headTitle($this->translate('Requested Items'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Requested Items') ?></h2>

    <?=$this->flashmessages()?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <? if (!empty($this->recordList)): ?>
      <form>
        <div class="toolbar">
          <?
            $hold_labels = [
              'title' => 'Title',
              'author' => 'Author',
              'callNumber' => 'Call Number',
              'itemStatus' => 'Item Status',
              'holdExpirationDate' => 'On Hold Until Date'
            ];
          ?>
          <span class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Sort By: <strong><?=$hold_labels[$this->sort]?></strong> <span class="caret"></span></button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><a href="/vufind/MyResearch/Holds?sort=title">Title</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=author">Author</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=callNumber">Call Number</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=itemStatus">Item Status</a></li>
              <li><a href="/vufind/MyResearch/Holds?sort=holdExpirationDate">On Hold Until Date</a></li>
            </ul>
          </span>
        </div>
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>

    <? $iteration = 0; ?>
    <? foreach ($this->recordList as $resource): ?>
      <? $iteration++; ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="result">
        <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
          <div class="checkbox">
            <label>
              <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" data-record-id="<?=$this->escapeHtmlAttr($resource->getSourceIdentifier() . '|' . $resource->getUniqueId());?>" />
            </label>
          </div>
        <? endif; ?>

        <?
          $coverDetails = $this->record($resource)->getCoverDetails('holds', 'small', $this->recordLink()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <? $thumbnail = ob_get_contents(); ?>
          <? ob_end_clean(); ?>
        <? endif; ?>
        <div class="media">
          <? if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <? endif ?>
          <div class="media-body">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                  . '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo '<span class="title">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>

            <? if (count($resource->getFormats()) > 0): ?>
              <?=$this->record($resource)->getFormatList() ?>
              <br/>
            <? endif; ?>
            <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['shelvingLocation'])): ?>
              <?=$this->escapeHtml($ilsDetails['shelvingLocation'])?>
              <br />
            <? endif; ?>

              <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
                <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
                <br />
              <? endif; ?>

            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
              <? if ($this->pickup): ?>
                <? foreach ($this->pickup as $library): ?>
                  <? if ($library['locationID'] == $ilsDetails['location']): ?>
                    <? $pickupDisplay = $library['locationDisplay']; ?>
                    <? $pickupTranslate = true; ?>
                  <? endif; ?>
                <? endforeach; ?>
              <? endif; ?>
              <? if (empty($pickupDisplay)): ?>
                <? $pickupDisplay = $ilsDetails['location']; ?>
              <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
              <?=$this->transEsc('pick_up_location') ?>:
              <strong><?=$pickupTranslate ? $this->transEsc('location_' . $pickupDisplay, null, $pickupDisplay) : $this->escapeHtml($pickupDisplay)?></strong>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['available']) && $ilsDetails['available'] == true && (!(isset($ilsDetails['position']) && $ilsDetails['position'] > 1))): ?>
              <div class="text-success"><strong>Item Status:</strong> <?=$this->transEsc("hold_available") ?></div>
            <? else: ?>
              <div class="text-danger"><strong>Item Status:</strong> Not Yet Available</div>
            <? endif; ?>
            <div><?=$this->transEsc("hold_queue_position") ?>: <?=$this->escapeHtml($ilsDetails['position']) ?></div>

            </div>
            <div class="col-sm-4 col-xs-12">
            <? $callNumbers = $resource->getCallNumbers(); ?>
            <? if (!empty($callNumbers)): ?>
                <?=$this->transEsc('Call Number') ?>:
                <strong><?=$callNumbers[0]; ?></strong><br/>
            <? endif; ?>
            <? if ($ilsDetails['item_id']): ?>
                Barcode: <strong><?=$ilsDetails['item_id']?></strong><br/>
            <? endif; ?>

            <? if (!empty($ilsDetails['expire']) && $ilsDetails['status'] != 'ONHOLD'): ?>
              <strong>Request expires:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?><br/>
            <? elseif (!empty($ilsDetails['hold_until_date'])): ?>
               <strong>On Hold Until:</strong> <?=$this->escapeHtml($ilsDetails['hold_until_date']) ?><br/>
            <? endif; ?>

            <? if (!empty($ilsDetails['loan_type'])): ?>
              <span class="item-type"><?=$this->escapeHtml($ilsDetails['loan_type'])?></span>
              <br />
            <? endif; ?>
          </div>
          <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <? endif ?>
        </div>
        <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" title="'.$this->escapeHtmlAttr($resource->getCoinsOpenUrl()).'"></span>':''?>
      </div>
    <? endforeach; ?>
    <? if ($this->cancelForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You have no outstanding requests') ?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holds'])?>
</div>
</div>
