<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
?>
<!--<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>-->
<h4><?=$this->transEsc('Your Account')?></h4>
<div class="list-group">
  <?php //if ($this->userlist()->getMode() !== 'disabled'): ?>
    <!--<a href="<?//=$this->url('myresearch-favorites')?>"<?//=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?//=$this->transEsc('Favorites')?>
    </a>-->
  <?php //endif; ?>
  <?php if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <?php if ($this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-checkedout')?>" class="flex list-group-item checkedout<?=$this->active == 'checkedout' ? ' active' : ''?>">
        <span class="flex-col"><i class="fa fa-fw fa-book" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Checked Out Items')?></span>
        <span class="checkedout-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item flex<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
        <span class="flex-col"><i class="fa fa-fw fa-archive" aria-hidden="true"></i> <?=$this->transEsc('Storage Retrieval Requests')?></span>
        <span class="storageretrievalrequests-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-items flex<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
        <span class="flex-col"><i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?></span>
        <span class="illrequests-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item flex<?=$this->active == 'fines' ? ' active' : ''?>">
        <span class="flex-col"><i class="fa fa-fw fa-usd" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Fines')?></span>
        <span class="fines-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
      </a>
    <?php endif; ?>
      <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
        <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
      </a>
    <?php endif; ?>
    <?php if ($user && $user->libraryCardsEnabled()): ?>
      <a href="<?=$this->url('librarycards-home')?>" class="list-group-item<?=$this->active == 'librarycards' ? ' active' : ''?>">
        <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
      </a>
    <?php endif; ?>
  <?php if ($user): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="list-group-item">
      <i class="fa fa-fw fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
  <?php endif; ?>
</div>
<h4>Manage Requests</h4>
<div class="list-group">
  <?php if ($this->ils()->checkCapability('getMyHolds')): ?>
      <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item flex<?=$this->active == 'holds' ? ' active' : ''?>">
        <span class="flex-col"><i class="fa fa-fw fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Holds and Recalls')?></span>
        <span class="holds-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <a href="<?=$this->url('myresearch-storagerequest')?>" class="list-group-item<?=$this->active == 'storagerequest' ? 'active' : ''?>">
    <i class="fa fa-fw fa-shopping-cart" aria-hidden="true"></i> Mansueto Cart
  </a>
  <a href="https://requests.lib.uchicago.edu/illiad/illiad.dll" class="list-group-item external" target="_blank">
    <i class="fa fa-fw fa-file-text-o" aria-hidden="true"></i> Interlibrary Loan
  </a>
  <a href="http://forms.lib.uchicago.edu/lib/aon/aeon.php" class="list-group-item external" target="_blank">
    <i class="fa fa-fw fa-folder-open" aria-hidden="true"></i> Special Collections
  </a>
  <a href="https://www.lib.uchicago.edu/borrow/borrowing/my-accounts/" class="list-group-item external" target="_blank">
    <i class="fa fa-fw fa-question-circle-o" aria-hidden="true"></i> Accounts FAQ
  </a>
</div>
<h4>Course Reserves</h4>
<div class="list-group">
  <a href="https://acadtech-res.uchicago.edu/canvas/whichlogin/" class="list-group-item external" target="_blank">
    <i class="fa fa-fw fa-sticky-note-o" aria-hidden="true"></i> Canvas
  </a>
</div>
<?php if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <div class="list-group">
    <a href="<?=$this->url('myresearch-changepassword') ?>" class="list-group-item<?=$this->active == 'newpassword' ? ' active' : ''?>">
      <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
    </a>
  </div>
<?php endif; ?>
<?php if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Lists')?></h4>
  <div class="list-group">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <?php $lists = $user->getLists() ?>
    <?php foreach ($lists as $list): ?>
        <a href="<?=$this->url('userList', ['id' => $list['id']])?>" class="list-group-item<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>">
          <i class="fa fa-fw fa-bookmark-o" aria-hidden="true"></i> <?=$this->escapeHtml($list['title'])?>
        </a>
    <?php endforeach; ?>
    <a href="<?=$this->url('editList', ['id'=>'NEW'])?>" class="list-group-item">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
    <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
      <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
        <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
      </a>
    <?php endif; ?>
  </div>
<?php endif ?>
