<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<a class="search-filter-toggle visible-xs" href="#account-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?> col-sm-9">
    <h2><?=$this->transEsc('Your Profile')?></h2>
    <?=$this->flashmessages();?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <table class="table table-striped">
      <?=$this->renderArray(
          $arrTemplate, $this->user,
          [
            $this->transEsc('First Name') => 'firstname',
        $this->transEsc('Last Name') => 'lastname',
        $this->transEsc('Email') => 'email',
          ]
        )?>
    <?php if (count($this->pickup ?? []) > 1): // Skip form if only one location: ?>
        <tr><th><?=$this->transEsc('Preferred Library')?>:</th>
        <?php
        $selected = (strlen($this->profile['home_library'] ?? '') > 0)
              ? $this->profile['home_library'] : $this->defaultPickupLocation
        ?>
        <td>
          <form id="profile_form" class="form-inline" method="post">
            <select id="home_library" name="home_library" class="form-control">
              <?php foreach ($this->pickup as $lib): ?>
                <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->transEsc('location_' . $lib['locationDisplay'], null, $lib['locationDisplay'])?></option>
              <?php endforeach; ?>
            </select>
            <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Save')?>" />
          </form>
        </td>
      <?php endif; ?>
      <?
        echo $this->renderArray(
          $arrTemplate, $this->profile,
          [
          $this->transEsc('First Name') => 'firstname',
          $this->transEsc('Last Name') => 'lastname',
          $this->transEsc('Address') . ' 1' => 'address1',
          $this->transEsc('Address') . ' 2' => 'address2',
          $this->transEsc('Zip') => 'zip',
          $this->transEsc('City') => 'city',
          $this->transEsc('Country') => 'country',
          $this->transEsc('Phone Number') => 'phone',
          $this->transEsc('Mobile Number') => 'mobile_phone',
          $this->transEsc('Group') => 'group',
          $this->transEsc('Expires') => 'expiration_date'
          ]
        )?>
    </table>
  <?php if ('ils-none' !== $this->ils()->getOfflineMode() && isset($this->patronLoginView) && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
    <p><a href="https://www.lib.uchicago.edu/borrow/access-privileges/library-cards-and-account-information/" target="_blank" class="external">Keeping contact information current</a></p>
  </div>

<div class="<?=$this->layoutClass('sidebar')?> col-sm-3" id="myresearch-sidebar>
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>
</div>
