<?
    // Set up page title:
    $this->headTitle('Mansueto Cart');

    $grouperGroups = $this->ServiceLinks()->getGrouperGroups();
    $canPage = $this->ServiceLinks()->isMemberOf('uc:applications:library:paging:authorized');

?>

<div class="<?=$this->layoutClass('mainbody')?> col-sm-9">
    <h2>Mansueto Cart</h2>
    <?=$this->flashmessages()?>

    <?php if ($canPage == false):?>
      <div class="alert alert-danger">
        <p>At this time, paging services are limited to current students, faculty, and staff of University of Chicago. Please monitor the Library website for changes to services as we reopen.</p>
      </div>
    <?php else: ?>

    <? if (empty($this->storagerequests)): ?>
        <p>You do not have any Mansueto requests waiting to be
submitted. For the status of requested Mansueto items, check <a
href="/vufind/MyResearch/Holds">Requested Items</a>.</p>
    <? else: ?>
            <p>Requested items will be retrieved by Library staff and made available for pickup at Regenstein.</p>
            <ul>
              <li>Most items will be available for pickup <strong>within 3 business days</strong>.</li>
              <li>You may place up to 200 requests per quarter, but the paging service may only be able to fill <strong>5 requests per person per day</strong>, depending on staffing and overall request volume.</li>
              <li><strong>You will receive an email notification when an item is available for pickup</strong>, which will include a link to reserve a 30-minute time slot to pick up your item(s). Items will be held for up to 7 days.</li>
              <li>Procedures for pickup will be sent to you when you reserve a time slot.</li>
            </ul>
	        <form action='/vufind/MyResearch/Storagerequest' method='post' name="mansuetoRequests">
            <p>
            <span id="asrselectallornone"></span>
	        <button class='request' name='action' type='submit' value='remove'>Remove selected items</button>
            </p>

		    <table class="table table-striped datagrid">
                <thead>
		            <tr>
				        <th/>
			            <th>Title</th>
				        <th>Call #</th>
				        <th>Copy</th>
		            </tr>
                </thead>
                <tbody>
		            <?php foreach ($this->storagerequests as $storagerequest): ?>
		                <tr>
                            <td><input name="remove[]" type="checkbox" value="<?=$storagerequest['bib']?>|<?=$storagerequest['barcode']?>"/></td>
		                    <?php 
		                        $title = $storagerequest['title'];
		                        if ($storagerequest['volumeNumber']) {
		                            $title .= ', ' .  $storagerequest['volumeNumber'];
		                        }
		                    ?>
		                    <td><?=$title?></td>
		                    <td><?=$storagerequest['callNumber']?></td>
		                    <td><?=$storagerequest['copyNumber']?></td>
		                </tr>
		            <?php endforeach; ?>
                </tbody>
		    </table>
	
		    <?php foreach ($this->storagerequests as $storagerequest): ?>
	            <input name='barcode[]' type='hidden' value='<?=$storagerequest['barcode']?>'/>
	            <input name='bib[]' type='hidden' value='<?=$storagerequest['bib']?>'/>
	        <?php endforeach; ?>

	        <label for='asrpickuplocation'>Select Pickup Location</label>
            <select id='asrpickuplocation' name='location'>
	            <!--<option value=''>Select...</option>-->
	            <option value='JRLMAIN'>Regenstein Lib, within 3 business days</option>
	            <!--<option value='MANSUETO'>Mansueto within 15 min during open hours</option>
	            <option value='CRERAR'>Crerar Lib, within 1 business day</option>
	            <option value='LAW'>D'Angelo Law Lib, within 1 business day</option>
	            <option value='ECKHART'>Eckhart Lib, within 1 business day</option>
	            <option value='SSAd'>Soc Serv Admin Lib within 1 business day</option>-->
	        </select>

            <p style="text-align: right;">	
	        <button class='request' name='action' type='submit' value='request'>Request all items</button>
            </p>
	    </form>
    <? endif; ?>

    <?php endif; ?><? // END if $canPage == false ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?> col-sm-3">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'storagerequests'))?>
</div>

<div class="clear"></div>
