<footer class="hidden-print container">
  <div class="footer-container">
    <div class="footer-column">
      <p id="uc_logo"><a title="The University of Chicago" href="http://www.uchicago.edu/">The University of Chicago</a></p>
      <!--<p><strong><?=$this->transEsc('Search Options')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
        <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
      </ul>-->
    </div>
    <div class="footer-column">
      <!--<p><strong><?=$this->transEsc('Find More')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
        <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
        <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
        <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
      </ul>-->
    </div>
    <div class="footer-column">
      <!--<p><strong><?=$this->transEsc('Need Help?')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
      </ul>-->
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
    <p id="copyright">&copy; 2015 
        <a href="http://www.lib.uchicago.edu/">The University of Chicago Library</a><br/>
        Powered by <a href="http://vufind.org/">VuFind</a> and 
        <a href="http://www.openlibraryenvironment.org/">OLE</a>
    </p>
  </div>
</footer>
