<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <a href="https://uchicago.edu/"><img class="footer-brand" src="/vufind/themes/phoenix/images/uc_logo.png"></a>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-center')->start(); ?>
      <?=$this->slot('footer-center')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
      <ul>
          <li><a href="https://accessibility.uchicago.edu/">University Accessibility</a></li>
          <li>Powered by <a href="http://vufind.org/">VuFind</a> and <a href="https://www.folio.org/">FOLIO</a></li>
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>
</footer>
