<?php $account = $this->auth()->getManager(); ?>

<?php /* Add the referring URL to the session
    * so we can always access the previous
    * page. Used to pass the referrer to
    * the knowledge tracker form */ 
    $_SESSION['Referrer'] = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : ''; ?>

<ul class="top-tabs">
    <li><a href="http://www.lib.uchicago.edu/">Library Home</a></li>
    <li><a href="http://www.lib.uchicago.edu/ask">Ask a Librarian</a></li>
    <li><a href="<?=$this->proxyUrl('http://www.lib.uchicago.edu/h/articlesplus')?>">ArticlesPlus</a></li>
    <li><a href="<?=$this->proxyUrl('http://www.lib.uchicago.edu/h/WorldCat')?>">WorldCat</a></li>
</ul>

<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars fa-lg" aria-hidden="true"></i>
  </button>
  <a role="button" class="navbar-brand hidden-md hidden-sm hidden-xs" href="<?=$this->url('home')?>">The University of Chicago Library Catalog</a>
  <a role="button" class="navbar-brand hidden-lg" href="<?=$this->url('home')?>">Library <span class="tagline">Catalog</span></a>
</div>
<?php if ($this->layout()->searchbox !== false): ?>
  <section class="visible-lg">
    <?/*Smart search box (default VuFind)*/?> 
    <?=$this->layout()->searchbox ?>
    <?/*Dumb browse box*/?>
    <?php $this->alphaBrowseTypes = $this->GetConfig()->getAlphabrowseSearchTypes(); ?>
    <?=$this->layout()->searchbox = $this->context($this)->renderInContext('alphabrowse/alphabrowseMini.phtml', ['searchClassId' => 'Solr']); ?>
  </section>
<?php endif; ?>
<?php if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <nav>
      <ul role="menu" class="nav navbar-nav navbar-right">
        <?php if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <?php endif; ?>
        <?php $cart = $this->cart(); if ($cart->isActive()): ?>
          <!--<li id="cartSummary">
            <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
              <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
              <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
            </a>
          </li>-->
        <?php endif; ?>
        <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
            <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon-disable-triangle" class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
          </li>
          <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
            <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
            <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
            <?php else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
            <?php endif; ?>
          </li>
            <?php if($account->dropdownEnabled()): ?>
              <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
                <div class="dropdown-menu">
                  <?=$this->render('myresearch/menu'); ?>
                </div>
              </li>
            <?php endif; ?>
        <?php endif; ?>
        <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <!--<li class="language dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <?php endforeach; ?>
            </ul>
          </li>-->
        <?php endif; ?>
      <li><a href="https://www.lib.uchicago.edu/research/help/catalog-help/" title="Help"><?=$this->transEsc("Help")?></a></li>
      </ul>
    </nav>
  </div>
<?php endif; ?>
