
#
# DATA FROM INDEXER = Label
#
# UChicago additions:


ArchivalCollections = Archives/Manuscripts
Audio               = Audio
AudioCass           = Audio Cassette
Book                = Book
Bluray              = Blu-ray Disc
DVD                 = DVD
Dissertations       = Dissertations
Ebook               = Ebook
Eresource           = E-Resource
Image               = Image
Globe               = Globe
Journals            = Journal
Kit                 = Kit
LaserDisc           = Laserdisc
Map                 = Map
Microform           = Microform
Model               = Model
MotionPicture       = Motion Picture
Music               = Music Recording
Phonograph          = LP
Photo               = Photograph
Print               = Print
Serial              = Journal
SheetMusic          = Music Score
Spoken              = Spoken Word Recording
Software            = Software
CD                  = CD
SoundRecording      = Sound Recording
StreamingAudio      = Streaming Audio
StreamingVideo      = Streaming Video
Text                = Text
Video               = Video
tapeVideo           = Video Cassette
VideoGame           = Video Game
OnlineVideoGame     = Online Video Game
USfedGovDoc         = U.S. Federal Government Document
Unknown             = Unknown

