<?
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    //$toc = $this->driver->getTOC();
    $toc = $this->tab->getContent();
?>
<? if (!empty($toc)): ?>
  <strong><?=$this->transEsc('Table of Contents')?>: </strong>
  <ul class="toc">
    <? foreach ($toc['Syndetics'][0]['Content'] as $line): ?>
      <li><?=$this->escapeHtml($line)?></li>
    <? endforeach; ?>
  </ul>
<? else: ?>
  <?=$this->transEsc("Table of Contents unavailable")?>.
<? endif; ?>
