$(document).ready(function() {
  <? if (isset($this->searchDetails) && is_object($this->searchDetails)): ?>
    <? foreach ($this->searchDetails->getQueries() as $searchGroup): ?>
      <? $i = 0; foreach ($searchGroup->getQueries() as $search): ?>
        <? if (++$i == 1): ?>
          var new_group = addGroup('<?=addslashes($search->getString())?>', '<?=addslashes($search->getHandler())?>', '<?=$searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator()?>');
        <? else: ?>
          addSearch(new_group, '<?=addslashes($search->getString())?>', '<?=addslashes($search->getHandler())?>');
        <? endif; ?>
      <? endforeach; ?>
    <? endforeach; ?>
  <? else: ?>
    var group = addGroup();

    //hide limits when the page loads.
    $('fieldset').has('legend:contains("Limit To")').hide();

    //hide results per page on page load. 
    $('fieldset').has('legend:contains("Results per page")').hide();

    //hide year of publication on page load. 
    $('fieldset').has('legend:contains("Year of Publication")').hide();

    //hide boolean on page load. 
    $('input.btn-primary').eq(0).hide();
    $('label[for="search_bool0"]').hide();
    $('select#search_bool0').hide();
  <? endif; ?>
});
