<h2><?=$this->transEsc("Send us your feedback!")?></h2>
<p>Thank you for providing feedback on your experience using the Library Catalog. You may use this form to report problems, ask questions, or make comments about the Catalog.</p>
<p>To report an error in a specific record in the Catalog, please use the "Report a Record Problem" link found in the record.</p>
<p>If you are trying to view your checked out items or renew your books, the functionality is temporarily unavailable in the Catalog. Please either ask at a circulation desk or use the <a href="http://lib.uchicago.edu/e/ask/contactcirc.html">Contact Circulation form</a> to ask Library staff to send you a list of what you have checked out or to renew your books.</p><br/>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Library Catalog Known Issues</h3>
  </div>
    <ul class="list-group">
      <li class="list-group-item">Catalog information may be slow to appear. Our software developers are actively working to address this problem. The Library apologizes for the delay and appreciates your patience.</li>
      <li class="list-group-item">Exporting records to citation management software (e.g. Zotero and EndNote) may not transfer all information. EndNote users are encouraged to download an <a href="http://guides.lib.uchicago.edu/content.php?pid=114489&amp;sid=989559">updated connection file</a> from our EndNote Research Guide.</li>
    </ul>
  <div class="panel-footer">For additional known issues, please see "Outstanding Issues" in our <a href="http://lib.uchicago.edu/e/using/catalog/about.html#issues">About the Catalog</a> page.</div>
</div>
<br/>

<form class="form-vertical" id="KnowledgeTracker" name="KnowledgeTracker" method="post" action="<?=$this->formUrl?>" abineguid="<?=$this->abineguid?>">
  <input type="hidden" id="library" name="library" value="<?=$this->libId?>" />
  <input type="hidden" id="formSuccess" value="<?=$this->transEsc("Form Submitted!")?>"/>
  <input type="hidden" id="feedbackSuccess" value="<?=$this->transEsc("Thank you for your feedback.")?>"/>
  <input type="hidden" id="feedbackFailure" value="<?=$this->transEsc("An error has occurred")?>"/>
  <input type="hidden" id="pageUrl" name="page_url" value="<?=$this->pageUrl?>" readonly >
  <input type="hidden" id="refUrl" name="referring_page" value="<?=$this->refUrl?>" readonly >
  <div class="form-group">
    <label for="tasks"><?=$this->transEsc("Please briefly describe the types of tasks you attempted to complete with the Library Catalog")?></label>
      <textarea id="tasks" class="form-control" name="tasks" placeholder="Examples: search for a book by title; look for works by an author."></textarea>
  </div>
  <div class="form-group">
    <label for="question"><?=$this->transEsc("Please share any comments about your experience with the Library Catalog")?></label>
      <textarea id="question" class="form-control" name="question"></textarea>
  </div>
  <div class="form-group">
    <label for="affiliation"><?=$this->transEsc("Affiliation")?></label>
    <select multiple class="form-control" id="affiliation" name="affiliation">
        <option>Faculty</option>
        <option>Graduate/professional student</option>
        <option>College student</option>
        <option>Library staff</option>
        <option>Staff</option>
        <option>Alumni</option>
        <option>I am not affiliated with the University of Chicago.</option>
        <option>Other</option>
    </select>
    <span id="affilHelp" class="help-block">Please select</span>
  </div>
  <div class="form-group">
    <label for="name"><?=$this->transEsc("feedback_name")?></label>
      <input type="text" id="name" class="form-control" name="name"/>
  </div>
  <div class="form-group">
    <label for="email"><?=$this->transEsc("Email")?></label>
      <input type="email" id="email" class="form-control" name="email" aria-describedby="emailHelp"/>
      <span id="emailHelp" class="help-block">If you would like a response from Library staff, please provide a name and email address.</span>
  </div>
  <div class="form-group">
      <input type="submit" class="btn btn-primary" value="<?=$this->transEsc("Send")?>" />
  </div>
</form>
<p>This service is powered by KnowledgeTracker and complies with its 
<a href="http://www.knowledgetrackerlib.com/patron_terms_uc.pdf">privacy policy</a></p>

