<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings();
    $openUrl = $this->driver->openURLActive('holdings') ? $this->driver->getOpenURL() : false;
    $offlineMode = $this->ils()->getOfflineMode();
    $callNumDisplayText = '(Browse by Call Number)';
    $callNumLabel = 'Call Number:';
    // Account for replace_other_urls setting
    //$urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
    $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->Eholdings()->getEholdingLinks();//Replace default 856 urls with e-holdings from the 098 fields

    // E-resource links
    $hathiLink = $this->HathiLink()->getHathiLink();
    $hasFullTextOnline = $this->HathiLink()->hasFullTextOnline($holdings);
    $hasRelatedTextOnline = $this->HathiLink()->hasFullTextOnline($holdings, $related=true);

    // Whitelist for things without a barcode that need to display when a barcode isn't present.
    $itemStatusWhitelist = array('INPROCESS', 'ONORDER');

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
  <div class="alert alert-warning">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->currentPath()?>?login=true&amp;catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->currentPath() . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold modal-link" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrl || $hathiLink): ?>
  <div class="holdings-unit">
  <h3><?=$this->transEsc("Internet")?></h3>
  <? if (!empty($urls)): ?>
      <?/*For now, only display a browse link if the first e-holding has a callnumber - Fix later*/?>
      <? if (isset($urls[0]['callnumber'])):?>
        <br/><h4><span><?=$this->transEsc($callNumLabel)?> </span><?=$urls[0]['callnumber']?></h4> <a href="<?= $this->url('home')?>alphabrowse/Home?source=lcc&amp;from=<?=$this->escapeHtml($urls[0]['callnumber'])?>"
           class="ablink"><?=$callNumDisplayText?></a><br/>
      <?endif;?>
    <? foreach ($urls as $current): ?>
      <? $linkText = (!empty($current['text']) ? ': '.$current['text'] : ''); ?>
      <div>
        <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="eLink text-success"><?=$this->escapeHtml($this->Eholdings()->getEholdingsLinkText($current['type']) . $linkText)?></a> <?=$current['desc']?><br/>
      </div>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrl): ?><?=$this->openUrl($openUrl);?><? endif; ?>
  <?/*Build a Hathi link for records with a 903 field = to "Hathi" or records with a bib# beginning with ocm or ocn.*/?>
  <? if ($hathiLink) : ?>
    <?=$hathiLink?>    
  <? endif; ?>
  <?=$this->record($this->driver)->getPreviewLink()?>
  </div>
<? endif; ?>

<? foreach ($holdings as $holding): ?>

<?/*Convenience variable for e-resources*/?>
<?$isFullTextOnline = $holding['location'] == 'FullText'?>
<?$isRelatedTextOnline = $holding['location'] == 'Related'?>

<div class="holdings-unit">

<?//Bound-withs?>
<? if (!empty($holding['items'][0]['boundwiths'])): ?>
  <h3>This item is bound with: </h3>
  <p><?=!empty($holding['items'][0]['boundwiths']['cn']) ? '<strong>' . $this->transEsc($callNumLabel) . ' </strong>' . $holding['items'][0]['boundwiths']['cn'] : ''; ?></p>
  <p>
  <? foreach ($holding['items'][0]['boundwiths'] as $key): ?>
    <? if (array_key_exists('title', $key)):?>
      <?="<a href='" . $key['url'] . "'>" . $key['title'] . "</a>"; ?>
    <?endif;?><br/>
  <? endforeach; ?></p>
<? endif; ?>
<?//End Bound-withs?>

<h3><?=$this->transEsc('location_' . $holding['location'], array(), $holding['location'])?></h3>
<? //print_r($holding);?>
<? if ($isFullTextOnline):?>
  <br/><strong><?=$this->transEsc("Available via:")?></strong>
<? endif; ?>
<? if ($isRelatedTextOnline):?>
  <br/><strong><?=$this->transEsc("Related Links:")?></strong>
<? endif; ?>

<?/*Get the first barcode to pass to the map links*/
  $firstBarcode = $this->tab->getFirstBarcode($holding);?>
<span class="maplink"><?=$this->ServiceLinks()->maps($this->driver->getUniqueID(), $firstBarcode)?></span><br/>

<?/*Callnumbers*/?>
<? $callNos = $this->tab->getUniqueCallNumbersPhoenix($holding['items']); if (!empty($callNos)): ?>
<? $hasCallNos = !empty($callNos['display']); ?>
<?foreach ($callNos['display'] as $numKey => $callNo): ?>
   <h4><span><?=$hasCallNos ? $this->transEsc($callNumLabel) . ' ' : ''?></span> <?=$this->escapeHtml($callNo)?></h4>
   <? $source = ($callNos['typeid'][$numKey] == '3') ? 'dewey' : 'lcc'; ?>
   <a href="<?= $this->url('home')?>alphabrowse/Home?source=<?=$source?>&amp;from=<?=$this->escapeHtml($callNos['sort'][$numKey])?>"
      class="ablink"><?=$callNumDisplayText?></a><br/>
 <? endforeach; ?>

<table class="holdings-table table" data-display="<?=$this->tab->getDisplayNumber()?>">
  <caption><?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?></caption>
  <!--<tr>
    <th><?=$hasCallNos ? $this->transEsc($callNumLabel) . ' ' : ''?></th>
    <td>
      <?foreach ($callNos['display'] as $numKey => $callNo): ?>
        <?=$this->escapeHtml($callNo)?>
        <a href="<?= $this->url('home')?>alphabrowse/Home?source=lcc&from=<?=$this->escapeHtml($callNos['sort'][$numKey])?>"
           class="ablink"><?=$callNumDisplayText?></a><br/>
      <? endforeach; ?>
    </td>
  </tr>-->
  <? endif; ?>
  <? foreach ($this->ils()->getHoldingsTextFieldNames() as $textField): ?>
    <? if (!empty($holding[$textField])): ?>
      <tr class="section">
        <? // Translation for summary is a special case for backwards-compatibility ?>
        <th><?=$textField == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textField))?>:</th>
        <td>
          <? foreach ($holding[$textField] as $current): ?>
            <? if(!empty($current)):?>
                <div typeof="Enumeration"><?=$this->escapeHtml($current)?></div>
            <?endif;?>
          <? endforeach; ?>
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? foreach ($holding['items'] as $row): ?>
    <?/*E-holding links if they exist*/?>
    <? if (isset($row['eHolding']['uri'])):?>
        <br/><a href="<?=$this->proxyUrl($row['eHolding']['uri'])?>" class="fulltext eLink text-success"><?=$this->transEsc("Full text online")?></a>
    <? endif; ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? $checkStorageRetrievalRequest = (isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest']); ?>
    <? $checkILLRequest = (isset($row['checkILLRequest']) && $row['checkILLRequest']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != "" || (in_array($row['status'], $itemStatusWhitelist))): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <? if (isset($row['itemTypeCode']) && $row['itemTypeCode'] != "stks"):?>
                  <span>Loan period: <?=$row['itemTypeName']?>&nbsp;</span>
               <?endif;?>

               <span class="text-success"><?=$this->transEsc($row['status'] == 'AVAILABLE-AT-MANSUETO' ? 'AVAILABLE' : $row['status'])?><link property="availability" href="http://schema.org/InStock" /></span>
               <?=$this->ServiceLinks()->scanAndDeliver($row)?>
               <?=$this->ServiceLinks()->asr($row)?>
               <?=$this->ServiceLinks()->dllStorage($row)?>
               <?=$this->ServiceLinks()->cantFindIt($row)?>
               <?=$this->ServiceLinks()->debugging($row)?>
              <? if (isset($row['link']) && $row['link']): ?>
                <!--<a style="display:inline-block" class="<?//=$check ? 'checkRequest ' : ''?>inlineblock modal-link placehold" href="<?//=$this->recordLink()->getRequestUrl($row['link'])?>" title="<?//=$this->transEsc($check ? "Check Hold" : "Place a Hold")?>"><i class="fa fa-flag"></i>&nbsp;<?//=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>-->
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?>modal-link placeStorageRetrievalRequest" href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" title="<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
              <? if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>inlineblock modal-link placeILLRequest" href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"  title="<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <? if ($row['status'] == 'ANAL'): ?>
                 To check availability
                 <? $c = array_shift(explode(' ', $this->driver->getCallNumber())); ?>
                 <a href="/vufind/alphabrowse/home?from=<?=$c;?>&source=lcc">consult the series record</a>.
              <? else: ?>
              <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                <?/*Only display duedates for loaned items*/?>
                <? $duedate = ($row['status'] == 'LOANED' ? $this->tab->getDuedate($row) : '');?>
                <? if ($duedate == 'no due date unless recalled'): ?>
                <? $dueHtml = '&ndash; <span class="small">no due date unless recalled</span>'; ?>
                <? else: ?>
                <? $dueHtml = (!empty($duedate) ? '&ndash; <span class="small">' . $this->transEsc("Due") . ': ' . $this->escapeHtml($duedate) . '</span>' : '');?>
                <? endif; ?>
                <?=$dueHtml?>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? endif; //end if/else for row['status'] == 'ANAL'?>
              <?=$this->ServiceLinks()->asr($row)?>
              <?=$this->ServiceLinks()->borrowDirect($row)?>
              <?=$this->ServiceLinks()->getIt($row)?>
              <?=$this->ServiceLinks()->uBorrow($row)?>
              <?=$this->ServiceLinks()->debugging($row)?>
              <? if (isset($row['link']) && $row['link'] && !$row['claimsReturned']): ?>
                <!--<a class="<?//=$check ? 'checkRequest' : ''?> modal-link inlineblock placehold" href="<?//=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?//=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>-->
                <?=$this->ServiceLinks()->recall($row)?>
              <? endif; ?>
            <? endif; ?>
              <? /* Begin Items that are either Available or Unavailable */ ?>
                <?=$this->ServiceLinks()->aeon($row)?>
                <?=$this->ServiceLinks()->altText($row, $this->driver->getFormats())?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>

</div><!--/.holdings-unit-->
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>
