<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $offlineMode = $this->ils()->getOfflineMode();
    $callNumDisplayText = '(Browse by Call Number)';
    $callNumLabel = 'Call Number:';
    // Account for replace_other_urls setting
    //$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $urls = $this->Eholdings()->getEholdingLinks();//Replace default 856 urls with e-holdings from the 928 fields (previously 098)
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = ['holdings' => []];
        $offlineMode = 'ils-offline';
    }

    $bib = $this->driver->getUniqueID();
    $isSfxStub = strtolower(substr($bib, 0, 3)) == 'sfx'; 

    // E-resource links
    $hathiLink = $this->HathiLink()->getHathiLink();
    $hasFullTextOnline = $this->HathiLink()->hasFullTextOnline($holdings);
    $hasRelatedTextOnline = $this->HathiLink()->hasFullTextOnline($holdings, $related=true);

    // Whitelist for things without a barcode that need to display when a barcode isn't present.
    $itemStatusWhitelist = array('INPROCESS', 'ONORDER');

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());

    // Item locations that are off site storage
    $OFFSITE = ['btaaspr'];
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<? if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<? endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrlActive || $hathiLink || $isSfxStub): ?>
  <div class="holdings-locpanel">
  <div class="locpanel-heading online">
  <h2><?=$this->transEsc("Online")?></h2><br/>
  <? if (!empty($urls)): ?>
      <?/*For now, only display a browse link if the first e-holding has a callnumber - Fix later*/?>
      <? if (isset($urls[0]['callnumber'])):?>
        <h3><span><?=$this->transEsc($callNumLabel)?> </span><?=$urls[0]['callnumber']?></h3> <a href="<?= $this->url('home')?>alphabrowse/Home?source=lcc&amp;from=<?=$this->escapeHtml($urls[0]['callnumber'])?>"
           class="ablink"><?=$callNumDisplayText?></a><br/>
      <?endif;?>
  <? endif; ?>
  </div><!--/.locpanel-heading online-->
  <div id="e-links" class="holdings-unit" data-issns="<?=implode(',', $this->driver->getISSNs())?>">
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <? $linkText = (!empty($current['text']) ? ': '.$current['text'] : ''); ?>
      <div>
        <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="eLink"><?=$this->escapeHtml($this->Eholdings()->getEholdingsLinkText($current['type']) . $linkText)?></a> <?=$current['desc']?><br/>
      </div>
    <? endforeach; ?>
  <? endif; ?>

  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>

  <?/*Build a Hathi link for records with a 903 field = to "Hathi" or records with a bib# beginning with ocm or ocn.*/?>
  <? if ($hathiLink) : ?>
    <?=$hathiLink?>    
  <? endif; ?>
  <?=$this->record($this->driver)->getPreviewLink()?>
  <?=$this->ServiceLinks()->altText($this->driver->getFormats(), $bib)?>
  </div><!--/#e-links-->
  </div><!--/.holdings-locpanel-->
<? endif; ?>
<? foreach ($holdings['holdings'] as $holding): ?>
<?/*Convenience variable for e-resources*/?>
<?$isFullTextOnline = $holding['location'] == 'FullText'?>
<?$isRelatedTextOnline = $holding['location'] == 'Related'?>

<?//Bound-withs?>
<? if (!empty($holding['items'][0]['boundwiths'])): ?>
  <h3>This item is bound with: </h3>
  <p><?=!empty($holding['items'][0]['boundwiths']['cn']) ? '<strong>' . $this->transEsc($callNumLabel) . ' </strong>' . $holding['items'][0]['boundwiths']['cn'] : ''; ?></p>
  <p>
  <? foreach ($holding['items'][0]['boundwiths'] as $key): ?>
    <? if (array_key_exists('title', $key)):?>
      <?="<a href='" . $key['url'] . "'>" . $key['title'] . "</a>"; ?>
    <?endif;?><br/>
  <? endforeach; ?></p>
<? endif; ?>
<?//End Bound-withs?>

<div class="holdings-locpanel">
<div class="locpanel-heading">
<h2>
  <? // Get the raw location text. This contains the holdings id # and other such things ?>
  <? // Break it into component parts and use it for different purposes ?>
  <? $rawLocationText = $this->transEsc('location_' . $holding['location'], [], $holding['location']); ?>
  <? $locationText = implode('-', explode('-', $rawLocationText, -1)); ?>
  <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
    <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
  <? else: ?>
    <?=$locationText?>
  <? endif; ?>
</h2>

<? /* Loop over textual (summary) holdings and separate them for later use */?>
<? if (isset($holding['textfields'])): ?>
  <? $unboundIssues = []; ?>
  <? $unboundSupplements = []; ?>
  <? $holdingsNotes = []; ?>
  <? $otherTextualHoldings = []; ?>
    <? foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
      <? $isUnboundIssues = $textFieldName == 'unbound issues'; ?>
      <? $isUnboundSupplements = $textFieldName == 'unbound supplements'; ?>
      <? $isHoldingsNotes = $textFieldName == 'holdings notes'; ?>
      <? if ($isHoldingsNotes): ?>
        <? $holdingsNotes['textfields'] = [$textFieldName => $textFields]; ?>
      <? elseif ($isUnboundIssues): ?>
        <? $unboundIssues['textfields'] = [$textFieldName => $textFields]; ?>
      <? elseif ($isUnboundSupplements): ?>
        <? $unboundSupplements['textfields'] = [$textFieldName => $textFields]; ?>
      <? else: ?>
        <? $otherTextualHoldings[$textFieldName] = ['textfields' => $textFields]; ?>
      <? endif; ?>
    <? endforeach; ?>
<? endif; ?>

<? /* Variables for checking the status of Library Has*/?>
<? $flatLibHas = call_user_func_array('array_merge', $otherTextualHoldings['issues']); ?>
<? $libHasCount = count($flatLibHas); ?>
<? $emptyLibHas = empty(trim($flatLibHas[0])); ?>
<? $doesNotHaveLibraryhas = ($libHasCount <= 1 && $emptyLibHas); ?>

<? /* Variables for checking the status of holdings notes*/?>
<? $flatHoldingsNotes = call_user_func_array('array_merge', $holdingsNotes['textfields']); ?>
<? $holdingNotesCount = count($flatHoldingsNotes); ?>
<? $emptyHoldingNotes = empty(trim($flatHoldingsNotes[0])); ?>
<? $noHoldingsNotes = ($holdingNotesCount <= 1 && $emptyHoldingNotes); ?>

<?/*Get the first barcode to pass to the map links*/ ?>
<? $firstBarcode = $this->tab->getFirstBarcode($holding);?>

<?/*Callnumbers*/?>
<? $callNos = $this->tab->getUniqueCallNumbersPhoenix($holding['items']); if (!empty($callNos)): ?>

<? $hasCallNos = !empty($callNos['display']); ?>
<?foreach ($callNos['display'] as $numKey => $callNo): ?>
   <?=$this->ServiceLinks()->maps(trim($locationText), $this->escapeHtml(trim($callNos['sort'][$numKey])), trim($callNos['prefix']))?>
   <br/><h3><span><?=$hasCallNos ? $this->transEsc($callNumLabel) . ' ' : ''?></span> <?=$this->escapeHtml($callNo)?></h3>
   <? $source = ($callNos['typeid'][$numKey] == '3') ? 'dewey' : 'lcc'; ?>
   <a href="<?= $this->url('home')?>alphabrowse/Home?source=<?=$source?>&amp;from=<?=$this->escapeHtml($callNos['sort'][$numKey])?>"
      class="ablink"><?=$callNumDisplayText?></a><br/>
 <? endforeach; ?>
</div><!--/.locpanel-heading-->

<div class="holdings-unit">
<? if ($isFullTextOnline):?>
  <strong><?=$this->transEsc("Available via:")?></strong>
<? endif; ?>
<? if ($isRelatedTextOnline):?>
  <br/><strong><?=$this->transEsc("Related Links:")?></strong>
<? endif; ?>

  <? /* Use the stored and separated textual (summary) holdings */?>
  <? if (isset($holding['textfields'])): ?>
      <? if (!$noHoldingsNotes): ?>
        <p class="holdings-notes"><strong>Holdings notes: </strong> 
          <? foreach ($holdingsNotes['textfields']['holdings notes'] as $holdingNote): ?>
            <?=$holdingNote?>
          <? endforeach; ?>
        </p>
      <? endif; ?>

      <? if (!$doesNotHaveLibraryhas): ?>
        <? /* The number of ownership types*/?>
        <? $numTextHoldings = count($otherTextualHoldings); ?>
        <? $summDivClass = ($numTextHoldings > 2 ? 'col-sm-4' : 'col-sm-6') ;?>
        <div class="section row libraryhas">
          <h5>Library has:</h5>
          <? foreach ($otherTextualHoldings as $textFieldName => $textFieldArray): ?>
              <? // Translation for summary is a special case for backwards-compatibility ?>
              <div class="summary-holdings <?=$summDivClass?>" data-display="<?=$this->tab->getDisplayNumber()?>">
                <h6>
                    <? if ($textFieldName == 'summary'): ?>
                        <?=$this->transEsc("Volume Holdings")?>
                    <? elseif ($textFieldName == 'issues'): ?>
                        <?=$this->transEsc("Issues/Volumes")?>
                    <? else: ?>
                        <?=$this->transEsc(ucfirst($textFieldName))?>
                    <? endif; ?>
                </h6>
                <ul>
                <? foreach ($textFieldArray['textfields'] as $current): ?>
                  <li typeof="Enumeration"><?=$this->escapeHtml($current)?></li>
                <? endforeach; ?>
                </ul>
              </div>
          <? endforeach;?>
        </div>
      <? endif; ?>

      <? /*Unbound issues and unbound supplements*/ ?>
      <? $splitChar = '^'; ?>
      <? /*Unbound Suplements*/?>
      <? if ($unboundIssues): ?>
        <? $unboundLocation = explode($splitChar, $unboundIssues['textfields']['unbound issues'][0])[1]; ?>
        <? foreach ($unboundIssues['textfields'] as $textFieldName => $textFields): ?>
          <table class="holdings-table table unbound" data-display="<?=$this->tab->getDisplayNumber()?>">
            <thead>
              <tr>
                <th colspan="3">
                    <h5><?=$this->transEsc(ucfirst($textFieldName))?>:</h5>
                    <span class="unbound-location"><?=$unboundLocation?></span>
                </th>
              </tr>
            </thead>
            <tbody>
              <? foreach ($textFields as $current): ?>
                <? $arr = explode($splitChar, $current); ?>
                <? if (!empty(trim($arr[0]))): ?>
                  <tr vocab="http://schema.org/" typeof="Offer">
                    <th><?=$this->escapeHtml($arr[0])?></th>
                    <td>
                      Check shelf for availability
                      <link property="availability" href="http://schema.org/InStock"/>
                      <span class="loan-period">Building use only</span>
                    </td>
                  </tr>
                <? endif; ?>
              <? endforeach;?>
            </tbody>
          </table>
        <? endforeach;?>
      <? endif; ?>

      <? /*Unbound supplements*/ ?>
      <? if ($unboundSupplements): ?>
        <? $unboundLocation = explode($splitChar, $unboundSupplements['textfields']['unbound supplements'][0])[1]; ?>
        <? foreach ($unboundSupplements['textfields'] as $textFieldName => $textFields): ?>
          <table class="holdings-table table unbound" data-display="<?=$this->tab->getDisplayNumber()?>">
            <thead>
              <tr>
                <th colspan="3">
                    <h5><?=$this->transEsc(ucfirst($textFieldName))?>:</h5>
                    <span class="unbound-location"><?=$unboundLocation?></span>
                </th>
              </tr>
            </thead>
            <tbody>
              <? foreach ($textFields as $current): ?>
                <? $arr = explode($splitChar, $current); ?>
                <? if (!empty(trim($arr[0]))): ?>
                  <tr vocab="http://schema.org/" typeof="Offer">
                    <th><?=$this->escapeHtml($arr[0])?></th>
                    <td>
                      Check shelf for availability
                      <link property="availability" href="http://schema.org/InStock"/>
                      <span class="loan-period">Building use only</span>
                    </td>
                  </tr>
                <? endif; ?>
              <? endforeach;?>
            </tbody>
          </table>
        <? endforeach;?>
      <? endif; ?>

  <? endif; ?>

<? // Create a boolean to see if holding has items ?>
<? $hasItems = false; ?>
<? foreach ($holding['items'] as $item): ?>
  <? if (array_key_exists('holdtype', $item)): ?>
    <? $hasItems = true; break; ?>
  <? endif; ?>
<? endforeach; ?>

<? // Only display availability heading if holding has items ?>
<? if ($hasItems): ?>
    <h5>Availability:</h5>
    <? if($unboundIssues || !$doesNotHaveLibraryhas): ?>
      <span class="holding-location"><?=$locationText?></span>
    <? endif; ?>
<? endif; ?>

<table class="holdings-table table" data-display="<?=$this->tab->getDisplayNumber()?>">
  <caption><?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($locationText)?></caption>
  <!--<tr>
    <th><?=$hasCallNos ? $this->transEsc($callNumLabel) . ' ' : ''?></th>
    <td>
      <?foreach ($callNos['display'] as $numKey => $callNo): ?>
        <?=$this->escapeHtml($callNo)?>
        <a href="<?= $this->url('home')?>alphabrowse/Home?source=lcc&from=<?=$this->escapeHtml($callNos['sort'][$numKey])?>"
           class="ablink"><?=$callNumDisplayText?></a><br/>
      <? endforeach; ?>
    </td>
  </tr>-->
  <? endif; ?>
  <? foreach ($holding['items'] as $row): ?>
    <?/*E-holding links if they exist*/?>
    <? if (isset($row['eHolding']['uri'])):?>
        <br/><a href="<?=$this->proxyUrl($row['eHolding']['uri'])?>" class="fulltext eLink"><?=$this->transEsc("Full text online")?></a>
    <? endif; ?>
    <?
      // AJAX Check record?
      $check = isset($row['check']) && $row['check'];
      $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
      $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
    ?>
    <? if (isset($row['barcode']) && $row['barcode'] != "" || (in_array($row['status'], $itemStatusWhitelist))): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <? if ($row['number']):?>
        <th><?=$this->escapeHtml($row['number'])?></th>
        <? endif; ?>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>

               <span class="text-success">
                   <?=$this->transEsc($row['status'] == 'AVAILABLE-AT-MANSUETO' ? 'Available' : $row['status_name'])?><link property="availability" href="http://schema.org/InStock" />
                   <? if (isset($row['itemTypeCode']) && !empty($row['itemTypeName'])):?>
                      <span class="loan-period">Loan period: <?=$row['itemTypeName']?>&nbsp;</span>
                   <?endif;?>
               </span>
               <span class="service-links">
               <?=$this->ServiceLinks()->asr($row)?>
               <?=$this->ServiceLinks()->dllStorage($row)?>
               <?=$this->ServiceLinks()->cantFindIt($row)?>
               <?=$this->ServiceLinks()->inProcessAtMansueto($row)?>
               <?=$this->ServiceLinks()->request($row)?>
               <?=$this->ServiceLinks()->debugging($row)?>
              <? if (isset($row['link']) && $row['link']): ?>
                <!--<a class="<?=$check ? 'checkRequest ' : ''?>placehold" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>-->
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
              <? if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <? if ($row['status'] == 'ANAL'): ?>
                 To check availability
                 <? $callNumBreak = preg_split("/\s[a-zA-Z0-9]+\./", $callNos['sort'][$numKey]); ?>
                 <? if ($callNumBreak): ?>
                   <? $c = $callNumBreak[0]; ?>
                 <? else: ?>
                   <? $c = $callNos['sort'][$numKey]; ?>
                 <? endif; ?>
                 <a href="/vufind/alphabrowse/home?from=<?=$c;?>&source=lcc&consult=true">consult the series record</a>.
              <? else: ?>
              <? $statusClass = in_array(strtolower($row['status']), $OFFSITE) ? 'text-unknown' : 'text-danger' ?>
              <span class=<?=$statusClass?>><?=$this->transEsc($row['status'] == 'MISSING-FROM-MANSUETO' ? 'Missing' : $row['status_name'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                <?/*Only display duedates for loaned items*/?>
                <? $duedate = ($row['status'] == 'LOANED' ? $this->tab->getDueDate($row) : '');?>
                <? if ($duedate == 'no due date unless recalled'): ?>
                <? $dueHtml = '&ndash; <span class="small">no due date unless recalled</span>'; ?>
                <? else: ?>
                <? $dueHtml = (!empty($duedate) ? '&ndash; <span class="small">' . $this->transEsc("Due") . ': ' . $this->escapeHtml($duedate) . '</span>' : '');?>
                <? endif; ?>
                <?=$dueHtml?>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? endif; //end if/else for row['status'] == 'ANAL'?>
              <span class="service-links">
              <?=$this->ServiceLinks()->asr($row)?>
              <?=$this->ServiceLinks()->getIt($row)?>
              <?=$this->ServiceLinks()->debugging($row)?>
              <? if (isset($row['link']) && $row['link'] && !$row['claimsReturned']): ?>
                <!--<a class="<?//=$check ? 'checkRequest' : ''?> modal-link inlineblock placehold" href="<?//=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?//=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>-->
                <?=$this->ServiceLinks()->recall($row)?>
              <? endif; ?>
            <? endif; ?>
              <? /* Begin Items that are either Available or Unavailable */ ?>
                <?=$this->ServiceLinks()->aeon($row)?>
                <?=$this->ServiceLinks()->altText($this->driver->getFormats(), $bib, $row)?>
                <?=$this->ServiceLinks()->borrowDirect($row)?>
                <?=$this->ServiceLinks()->uBorrow($row)?>
                <?=$this->ServiceLinks()->scanAndDeliver($row)?>
                <?=$this->ServiceLinks()->offsite($row)?>
                </span><? /* END .service-links */?>
            <? if (isset($row['itemNotes'])): ?>
              <div class="item-notes">
                <?=$row['itemNotes']?>
              </div>
            <? endif; ?>
            <? if (isset($row['itemCallnumberDisplay'])): ?>
              <br/>
              <span class="location-change">
                <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
                <strong>Shelved as:</strong>
                <?=$row['itemCallnumberDisplay']?>
              </span>
            <? endif; ?>
            <? if (isset($row['itemLocation'])): ?>
              <br/>
              <span class="location-change">
                <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
                <strong>Shelved in:</strong>
                <?=$row['itemLocation']?>
              </span>
            <? endif; ?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        </td>
        <td width="2"></td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
</div><!--/.holdings-unit-->
</div><!--/.holdings-locpanel-->
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>
