<?php
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    $toc = $this->tab->getContent();
    if (!empty($toc) && array_key_exists('Syndetics', $toc)) {
        $toc = $toc['Syndetics'];
    } else {
        $toc = $this->driver->getTOC();
    }
?>
<?php if (!empty($toc)): ?>
  <strong><?=$this->transEsc('Table of Contents')?>: </strong>
  <ul class="toc">
    <?php if (isset($toc)): ?>
    <?php foreach ($toc as $line): ?>
      <li><?=$this->escapeHtml($line)?></li>
    <?php endforeach; ?>
    <?php endif; ?>
  </ul>
<?php else: ?>
  <?=$this->transEsc("Table of Contents unavailable")?>.
<?php endif; ?>
