<?php
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    ### UChicago customization ###
    $altData = $this->driver->tryMethod('getUCAltTOC');
    ### ./UChicago customization ###

    $toc = $this->tab->getContent();
    if (empty($toc)) {
        $driverToc = $this->driver->getTOC();
        if (!empty($driverToc)) {
            $toc['RecordDriver'] = $driverToc;
        }
    }
?>
  <strong><?=$this->transEsc('Table of Contents')?>: </strong>
  <? ### UChicago customization ### ?>
  <?php if (!empty($altData)): ?>
    <?php foreach ($altData as $provider => $content): ?>
      <?php if (!is_array($content)): // treat non-array content as raw HTML ?>
        <?=$content?>
      <?php else: ?>
        <ul class="toc">
        <?php foreach ($content as $line): ?>
          <li><?=$this->escapeHtml($line)?></li>
        <?php endforeach; ?>
        </ul>
      <?php endif; ?>
    <?php endforeach; ?>
    <?php else: ?>
      <?=$this->transEsc('Table of Contents unavailable')?>.
    <?php endif; ?>
  <? ### ./UChicago customization ### ?>
