<?php
  $this->headScript()->appendFile('facets.js');

  // Save results/options to $this so they are available to sub-templates:
  $this->results = $results = $this->recommend->getResults();
  $this->options = $options = $results->getOptions();

  $hierarchicalFacets = $this->recommend->getHierarchicalFacets();
  if ($hierarchicalFacets) {
    // jstree.min.js used to be injected by hierarchical-facet.js, but with deferred
    // processing it's called too late to append anything to the headers.
    $this->headScript()->appendFile('vendor/jsTree/jstree.min.js');
  }
?>
<!--<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>-->
<?php if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<?php endif; ?>
<?php $checkboxFilters = $results->getParams()->getCheckboxFacets(); ?>
<?php $checkboxesShown = false; ?>
<?php if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
      if ($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible']) {
        $checkboxesShown = true;
        break;
      }
    }
  ?>
  <?php if ($checkboxesShown): ?>
    <div class="checkboxFilter">
      <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results]); ?>
    </div>
  <?php endif; ?>
<?php endif; ?>
<?php $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : []; ?>
<?php $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?php $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
  <ul class="list-group filters">
    <li class="list-group-item title"><?=$this->transEsc('Remove Filters')?> <span class="pull-right gray hidden-sm">[Remove]</span></li>
    <?php foreach ($filterList as $field => $filters): ?>
      <?php foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>" title="<?=$this->transEsc('clear_tag_filter') ?>">
          <span class="pull-right flip"><i class="fa fa-times" aria-hidden="true"></i></span>
          <?php if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
        </a>
      <?php endforeach; ?>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<?php if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <?php foreach ($sideFacetSet as $title => $cluster): ?>
    <div class="facet-group" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <button class="title<?php if(in_array($title, $collapsedFacets)): ?> collapsed<?php endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" >
        <?=$this->transEsc($cluster['label'])?>
      </button>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<?php if(!in_array($title, $collapsedFacets)): ?> in<?php endif ?>">
          <?=$this->context($this)->renderInContext(
          'Recommend/SideFacets/facet.phtml',
              [
            'facet' => $title,
            'cluster' => $cluster,
            'collapsedFacets' => $collapsedFacets          ]
            ); ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
