<?php
  // Set page title.
  $this->headTitle($this->translate('Email Record'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Email Record') . '</li>';
?>
<h2><?=$this->transEsc('Email Record') ?>: <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span></h2>
<form class="form-horizontal" method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" name="emailRecord">
  <?=$this->flashmessages()?>
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" />
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" />
  <?=$this->render('Helpers/email-form-fields.phtml')?>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <p><i class="fa fa-info-circle"></i> Email services will be expanded. Forthcoming email features will include the ability to send multiple records simultaneously.</p>
    </div>
  </div>
</form>
