<?php
    // Set page title.
    $this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
        . '<li class="active">' . $this->transEsc('request_place_text') . '</li>';

    $isHold = $this->gatheredDetails['holdtype'] == 'hold';
    $isPage = $this->gatheredDetails['holdtype'] == 'page';
    $isDllStorage = isset($_GET['isDllStorage']);
    $isPickupAtReg = isset($_GET['isPickupAtReg']);

    $grouperGroups = $this->ServiceLinks()->getGrouperGroups();
    $canPage = $this->ServiceLinks()->isMemberOf('uc:applications:library:paging:authorized');
?>
<h2>
  <?php if ($isHold):?>
      <?php if($isPickupAtReg):?>
        <?=$this->transEsc('pick_up_at_reg_place_text')?>
      <?php else:?>
        <?=$this->transEsc('hold_place_text')?>
      <?php endif;?>
  <?php elseif ($isPage):?>
      <?php if($isDllStorage):?>
        <?=$this->transEsc('dll_page_place_text')?>
      <?php elseif($isPickupAtReg):?>
        <?=$this->transEsc('pick_up_at_reg_place_text')?>
      <?php else:?>
        <?=$this->transEsc('page_place_text')?>
      <?endif;?>
  <?php else: ?>
    <?=$this->transEsc('request_place_text')?>
  <?php endif; ?>
</h2>
<?php if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<?php endif; ?>

<div class="hold-form">
  <?php if (($isHold || $isPage) && $isPickupAtReg && $canPage == true):?>
    <p>Requested items will be retrieved by Library staff and made available for pickup at Regenstein.</p>
    <ul>
      <li>Most items will be available for pickup <strong>within 3 business days</strong>.</li>
      <li>You may place up to 200 requests per quarter, but the paging service may only be able to fill <strong>5 requests per person per day</strong>, depending on staffing and overall request volume.</li>
      <li><strong>You will receive an email notification when an item is available for pickup</strong>, which will include a link to reserve a 30-minute time slot to pick up your item(s). Items will be held for up to 7 days.</li>
      <li>Procedures for pickup will be sent to you when you reserve a time slot.</li>
    </ul>
  <?php elseif ($canPage == false && ($isPickupAtReg || $isHold)):?>
    <div class="alert alert-danger">
    <p>At this time, paging services are limited to current students, faculty, and staff of University of Chicago. Please monitor the Library website for changes to services as we reopen.</p>
    </div>
  <?php elseif ($isHold):?>
    <?php # Is a regular hold type from the Place Hold link ?>
    <?php # All Place Hold links lead here because they will never have the isPickupAtReg GET paramater and $isPickupAtReg will be false ?>
    <?php # Commented out the following and replaced with below due to COVID-19 ?>
    <!--<ul>
      <li>Placing a hold request on an item will cause the item to be held for pickup for you as soon as it is available.</li>
      <li><strong>Regenstein Closed Stack</strong> items will typically be available within <strong>1 business day</strong>.</li>
      <li><strong>In Transit</strong> items will typically be available within <strong>2-3 days</strong>.</li>
      <li><strong>In Process</strong> items will typically be available within <strong>7-10 days</strong>.</li>
      <li><strong>On Order</strong> items will typically be available for pickup within <strong>30-60 days</strong>, though some may take longer. <br/>Items ordered from outside North America and Europe may take as long as three to six months to arrive.</li>
      <li>Multiple requests for the same item are fulfilled in the order in which they are received.</li>
      <li>You will receive an email notice when the item is available for pickup.</li>
    </ul>-->
    <ul>
      <li>Placing a hold request on an item will cause the item to be held for pickup for you as soon as it is available.</li>
      <li><strong>In Process</strong> items will typically be available withing <strong>7-14 days</strong>.</li>
      <li><strong>On Order</strong> items will typically be available within <strong>30-60 days</strong>, though some may take longer. Items ordered from outside North America and Europe may take as long as three to six months to arrive.</li>
      <li>You will receive an email notice when the item is available for pickup.</li>
    </ul>
  <?php elseif ($isPage):?>
    <?php if($isDllStorage):?>
      <ul>
        <li>Requested items will be available for pickup at the D'Angelo Law Library circulation desk <strong>by 5 p.m. the following business day</strong>.</li>
        <li>Items requested for pickup at other libraries are typically available <strong>after two business days.</strong></li>
        <li> Building Use Only items may only be picked up at the D'Angelo Law Library.</li>
        <li>If a requested item is missing or otherwise unavailable, you will be notified by library staff.</li>
        <li>If you would like immediate assistance, please contact the D’Angelo Law Library circulation desk at (773) 702-0213 during our regular business <a href="https://www.lib.uchicago.edu/libraries/libraries-hours/">hours</a>.</li>
      </ul>
      <p>See <a href="https://www.lib.uchicago.edu/law/collections/storage/">D'Angelo Law Library Storage Collections</a> for more information.</p>
    <?php else:?>
      <p>If you can't find an item on the shelf, you can request that Library staff search for it.</p>
      <ul>
        <li>Most searches are resolved within two business days.</li>
        <li>If found, the item will be made available for pick up and you will be notified by email.
          <ul>
            <li>Items requested for pickup at their home location will be available as soon as they are located.</li>
            <li>Items requested for pickup at another location will be available within one business day after they are located.  </li>
          </ul>
        </li>
        <li>If not found, staff will notify you that it has been declared missing.</li>
        <li>If you would like immediate assistance, ask at any reference or circulation desk.</li>
      </ul>
    <?php endif; ?>
  <?php else: ?>
    <ul>
      <li>Recalling a <strong>loaned</strong> item from another user will cause the item to be due <strong>7 days after the date it is recalled</strong>.</li>
      <li>Recalling an item that is <strong>on hold</strong> or <strong>in transit for hold</strong> will cause the item to be due <strong>7 days after the date the prior user borrows the item</strong>.</li>
      <li>Multiple requests for the same item are fulfilled in the order in which they are received.</li>
      <li>You will receive an email notice when the item is available for pickup.</li>
    </ul>
  <?php endif; ?>

  <?php if (!($canPage == false && ($isPickupAtReg || $isHold))): ?>
    <div class="alert alert-info">
    <p>Due to limited staffing, requests placed over Winter Interim will take longer than usual.</p>
    </div>
    <div class="alert alert-info">
    <p>Requests can take sixty seconds to process. Please be patient when
    submitting this form.</p>
    </div>
      <form class="form-horizontal" method="post" name="placeHold">
        <?=$this->flashmessages()?>
        <label class="col-sm-3 control-label"><?=$this->transEsc('Title')?></label>
        <div class="col-sm-9">
          <p class="form-control-static"><?=$this->driver->getBreadcrumb() ?></p>
        </div>
        <?php if (in_array("comments", $this->extraHoldFields)): ?>
          <div class="form-group hold-comment">
            <label class="col-sm-3 control-label"><?=$this->transEsc("Comments")?>:</label>
            <div class="col-sm-9">
              <textarea rows="3" cols="20" name="gatheredDetails[comment]" class="form-control"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
            </div>
          </div>
        <?php endif; ?>

        <?php if (in_array("requiredByDate", $this->extraHoldFields)): ?>
          <div class="form-group hold-required-by">
            <label class="col-sm-3 control-label"><?=$this->transEsc("hold_required_by")?>:</label>
            <div class="col-sm-9">
              <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" class="form-control"/>
              (<?=$this->dateTime()->getDisplayDateFormat()?>)
            </div>
          </div>
        <?php endif; ?>

        <?php if ($this->requestGroupNeeded): ?>
          <div class="form-group hold-request-group">
            <?
              if (isset($this->gatheredDetails['requestGroupId']) && $this->gatheredDetails['requestGroupId'] !== "") {
                  $selected = $this->gatheredDetails['requestGroupId'];
              } else {
                  $selected = $this->defaultRequestGroup;
              }
           ?>
            <label class="col-sm-3 control-label"><?=$this->transEsc("hold_request_group")?>:</label>
            <div class="col-sm-9">
              <select id="requestGroupId" name="gatheredDetails[requestGroupId]" class="form-control">
              <?php if ($selected === false): ?>
                <option value="" selected="selected">
                  <?=$this->transEsc('select_request_group')?>
                </option>
              <?php endif; ?>
              <?php foreach ($this->requestGroups as $group): ?>
                <option value="<?=$this->escapeHtmlAttr($group['id'])?>"<?=($selected == $group['id']) ? ' selected="selected"' : ''?>>
                  <?=$this->transEsc('request_group_' . $group['name'], null, $group['name'])?>
                </option>
              <?php endforeach; ?>
              </select>
            </div>
          </div>
        <?php endif; ?>

        <?php if (in_array("pickUpLocation", $this->extraHoldFields)): ?>
          <?php
            if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
                $selected = $this->gatheredDetails['pickUpLocation'];
            } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
                $selected = $this->homeLibrary;
            } else {
                $selected = $this->defaultPickup;
            }
          ?>
          <?php if ($this->requestGroupNeeded): ?>
            <div class="form-group hold-pickup-location">
              <label id="pickUpLocationLabel" class="col-sm-3 control-label"><i></i> <?=$this->transEsc("pick_up_location")?>:
                <?php if (in_array("requestGroup", $this->extraHoldFields)): ?>
                  <noscript> (<?=$this->transEsc("Please enable JavaScript.")?>)</noscript>
                <?php endif; ?>
              </label>
              <div class="col-sm-9">
                <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" data-default="<?=$this->escapeHtmlAttr($selected)?>" class="form-control">
                  <?php if ($selected === false): ?>
                  <option value="" selected="selected">
                    <?=$this->transEsc('select_pickup_location')?>
                  </option>
                  <?php endif; ?>
                </select>
              </div>
            </div>
          <?php elseif ($isPickupAtReg): ?>
            <div class="form-group hold-pickup-location">
              <label class="col-sm-3 control-label"><?=$this->transEsc("pick_up_location")?>:</label>
              <div class="col-sm-9">
                <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" class="form-control">
                  <option value="JRLMAIN" selected="selected">Regenstein</option>
                </select>
              </div>
            </div>
          <?php elseif ($this->pickup): ?>
            <div class="form-group hold-pickup-location">
              <label class="col-sm-3 control-label"><?=$this->transEsc("pick_up_location")?>:</label>
              <div class="col-sm-9">
                <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" class="form-control">
                <?php if ($selected === false && count($this->pickup) > 1): ?>
                  <option value="" selected="selected">
                    <?=$this->transEsc('select_pickup_location')?>
                  </option>
                <?php endif; ?>
                <option value="JRLMAIN" selected="selected">Regenstein</option>
                <?php # Added the above line and commented out the below to support holds during COVID-19 ?>
                <?php foreach ($this->pickup as $lib): ?>
                  <!--<option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
                    <?=$this->transEsc('location_' . $lib['locationDisplay'], null, $lib['locationDisplay'])?>
                  </option>-->
                <?php endforeach; ?>
                </select>
              </div>
            </div>
          <?php else: ?>
            <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
          <?php endif; ?>
        <?php endif; ?>
        <div class="form-group">
          <div class="col-sm-9 col-sm-offset-3">
            <input class="btn btn-primary" type="submit" name="placeHold" value="<?=$this->transEsc('request_submit_text')?>"/>
          </div>
        </div>
      </form>
  <?php endif; ?> <!--./if (!($canPage == false && $isPickupAtReg))-->
</div>

<?
    // Set up hold script; we do this inline instead of in the header for lightbox compatibility:
    $this->inlineScript()->appendFile('hold.js');

    $js = <<<JS
        if ($.isReady) {
            setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
        } else {
            $(document).ready(function(){
                setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
            });
        }
JS;

    echo $this->inlineScript()->appendScript($js);
?>
