<!--245.phtml-->
<tr class="title">
   <td colspan="2">
      <h1>
      <? foreach($marcData as $data) : ?>
          <? echo htmlentities(implode(' ', $data['subfieldData'])) ?>
              <? if (!empty($data['vernacularData'])) : ?> 
                    <br/><? echo htmlentities(implode(' ', $data['vernacularData']));?>
              <? endif; ?>
      <? endforeach; ?>
      </h1>
   </td>
</tr>
