<!--atlasDefault.phtml-->
<!--<span id="<?=$marcData[0]['label']?>">
<? foreach($marcData as $data) : ?>
    <? if (!empty($data['subfieldData'])) : 
       echo htmlentities(implode(' ', $data['subfieldData'])) ?>
    <? endif; ?>   
    <? if (!empty($data['vernacularData'])) :
        echo '<br />';
        echo htmlentities(implode(' ', $data['vernacularData']));
        echo '<br />';
    ?>
    <? endif; ?>   
<? endforeach; ?>
</span>-->
