<!--atlasDefault.phtml-->
<!--<span id="<?=$marcData[0]['label']?>">
<? foreach($marcData as $data) : ?>
    <? if (!empty($data['subfieldData'])) : 
       echo implode(' ', $data['subfieldData']) ?>
    <? endif; ?>   
    <? if (!empty($data['vernacularData'])) :
        echo '<br />';
        echo implode(' ', $data['vernacularData']);
        echo '<br />';
    ?>
    <? endif; ?>   
<? endforeach; ?>
</span>-->
