<!--resultsAuthor.phtml-->
<? /*Display a link and the vernacular if there's data*/
   if(isset($data['subfieldData'])):
       $displayUrl = implode(' ', $data['subfieldData']);
       $link = $this->getAuthorBrowseLink($data['subfieldData']);?>

       <?=$this->view->transEsc('by')?> <a href="<?='/vufind/alphabrowse'.'/Home?source=author&amp;from='.urlencode(strip_tags(trim($link, ' ')))?>" class="<?=$data['label']?>"><?=$displayUrl ?></a><br/>
       <? if (!empty($data['vernacularData'])) :
           echo htmlentities(implode(' ', $data['vernacularData']));?><br />
       <? endif; ?>
<? endif; ?>
