<!--series.phtml-->
<? /*If it's a 490 field don't link it, otherwise link to a series browse*/
           if($data['currentField'] == 490) : ?>
               <? echo implode(' ', $data['subfieldData']) ?><br/>
               <? if (!empty($data['vernacularData'])) :
                      echo implode(' ', $data['vernacularData']);?><br />
               <? endif; ?>
           <? else: ?>
               <? 
                  $marcValue = implode(' ', $data['subfieldData']) ;

                  /*Get rid of subfield v only for the link (we still display it)*/
                  $v = $this->findKey('/^v/',$data['subfieldData']);
                      unset($data['subfieldData'][$v]);
                      $link = implode(' ', $data['subfieldData']);
                  ?>
                  <a href="<? echo '/vufind/alphabrowse'.'/home?source=series&from='.strip_tags(urlencode(trim($link)), ' ') ?>"><? echo $marcValue ?></a><br/>
                  <? if (!empty($data['vernacularData'])) :
                      echo implode(' ', $data['vernacularData']);?><br />
                  <? endif; ?>

           <?endif?>
