$(document).ready(function() {
  <? /* JS to edit an advanced search. */?>
  <? if (isset($this->searchDetails) && is_object($this->searchDetails)): ?>
    //hide basic search button.
    $('.basicSearchBtn').hide();
    <? $j = 0; foreach ($this->searchDetails->getQueries() as $searchGroup): ?>
      <? $i = 0; foreach ($searchGroup->getQueries() as $search): ?>
        //add a new search group, if necessary.
        if ($('#group<?=$j?>').length == 0) {
          addGroup('', '', '');
        }
        //add a new search box, if necessary.
        if ($('#search<?=$j?>_<?=$i?>').length == 0) {
          addSearch($('#add_search_link_<?=$j?>'), '', '');
        }
        //update the search text. 
        $('#search<?=$j?>_<?=$i?> input[type="text"]').val('<?=addslashes($search->getString())?>');

        //update the field pulldown.
        if ('<?=$search->getHandler()?>' != '') {
          $('#search_type<?=$j?>_<?=$i?>').val('<?=addslashes($search->getHandler())?>');
        }

        //update the group's join, if necessary.
        if (<?=$i?> > 0) {
            if (<?=($searchGroup->isNegated() ? 'true' : 'false')?>) {
                $('#search_bool<?=$j?>').val('NOT');
            } else {
                $('#search_bool<?=$j?>').val('<?=$searchGroup->getOperator()?>');
            }
        }
        <? $i++; ?>
      <? endforeach; ?>
      <? $j++; ?>
    <? endforeach; ?>
  <? endif; ?>
});
