$(document).ready(function() {
  <? /* JS to edit an advanced search. */?>
  <? if (isset($this->searchDetails) && is_object($this->searchDetails)): ?>
    //hide basic search button.
    $('.basicSearchBtn').hide();
    <? $j = 0; foreach ($this->searchDetails->getQueries() as $searchGroup): ?>
      <? $i = 0; foreach ($searchGroup->getQueries() as $search): ?>
        //add a new search group, if necessary.
        if ($('#group<?=$j?>').length == 0) {
          addGroup('', '', '');
        }
        //add a new search box, if necessary.
        if ($('#search<?=$j?>_<?=$i?>').length == 0) {
          addSearch($('#add_search_link_<?=$j?>'), '', '');
        }
        //update the search text. 
        $('#search<?=$j?>_<?=$i?> input[type="text"]').val('<?=addslashes($search->getString())?>');

        //update the field pulldown.
        if ('<?=$search->getHandler()?>' != '') {
          $('#search_type<?=$j?>_<?=$i?>').val('<?=addslashes($search->getHandler())?>');
        }

        //update the group's join, if necessary.
        if (<?=$i?> > 0) {
            if (<?=($searchGroup->isNegated() ? 'true' : 'false')?>) {
                $('#search_bool<?=$j?>').val('NOT');
            } else {
                $('#search_bool<?=$j?>').val('<?=$searchGroup->getOperator()?>');
            }
        }
        <? $i++; ?>
      <? endforeach; ?>
      <? $j++; ?>
    <? endforeach; ?>
  <? /* JS to convert the advanced search page to a basic search onload. */?>
  <? else: ?>
    //masquerade as basic search onload. 

    //change text input's name to 'lookfor'.
    $('#search_lookfor0_0').attr('name', 'lookfor');

    //change field pulldown's name to 'type'.
    $('#search_type0_0').attr('name', 'type');

    //hide 2nd and 3rd search box.
    $('#search0_2').find('a.delete').click();
    $('#search0_1').find('a.delete').click();
    
    //hide 'add search fields' links. 
    $('#group0Holder').hide();
    $('#add_search_link_0').hide();
    $('#what_is_a_field').hide();

    //add advanced search link.
    $('#advSearchP').prepend('<a href="#" id="advancedsearchlink" onclick="switchToAdvancedSearch(); return false;">Advanced Search</a> | ');

    //hide 'add search group' link. 
    $('#groupPlaceHolder').hide();

    //hide limits.
    $('fieldset').has('legend:contains("Limit To")').hide();

    //hide results per page.
    $('fieldset').has('legend:contains("Results per page")').hide();

    //hide year of publication.
    $('fieldset').has('legend:contains("Year of Publication")').hide();

    //hide advanced search buttons.
    $('.advancedSearchBtn').hide();

  <? endif; ?>

});
