<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();

    // When editing an advanced search, this page displays facets in the
    // sidebar. unset the facets that get displayed as limits. 
    unset($searchFilters['Language']);
    unset($searchFilters['Format']);
    unset($searchFilters['Location']);
    unset($searchFilters['unrecognized_facet_label']);
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
  }

  // Set up Javascript:
  // Step 1: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  // Step 2: Call the javascript to make use of the above
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  // Step 3: Build the page (if an override is necessary) 
  if ($this->buildPageOverride) {
    $this->headScript()->appendScript(
      $this->partial(
        $this->buildPageOverride, 
        array('searchDetails' => $searchDetails)
      )
    );
  }
?>

<?=$this->flashmessages()?>

<ul style="position: relative; top: 1px;" class="nav nav-tabs" id="homepageNavTabs">
  <li style="position: relative; top: 0px;" class="active"><a data-toggle="tab" href="#advSearch">Keyword</a></li>
  <li role="presentation"><a data-toggle="tab" href="#alphaBrowse">Begins With</a></li>
  <li class="hidden-xs which-search-links">
    <a href="#" id="searchtabinfolink" data-original-title="">Which one? <i class="fa fa-lg fa-info-circle"></i></a> <a href="https://youtu.be/RCgeTlgaipc">Video</a>
  </li>
</ul>

<div class="tab-content" id="homepageNavContent">
  <div class="tab-pane active" id="advSearch">
    <form role="search" class="advancedSearch" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
      <div class="row">
        <? if (empty($searchFilters)): ?>
        <div class="col-sm-12">
        <? else: ?>
        <div class="col-sm-9">
        <? endif; ?>
          <input type="hidden" name="sort" value="relevance">
          <div class="clearfix">
            <div id="groupJoin" class="form-inline pull-right hidden">
              <label for="groupJoinOptions"><?=$this->transEsc("search_match")?>:</label>
              <select id="groupJoinOptions" name="join" class="form-control">
                <option value="AND"<? if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
                <option value="OR"<? if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
              </select>
            </div>
          </div>

    <? ($groups == false) ? $group_count = 1 : $group_count = count($groups); ?>
    <? for ($g = 0; $g < $group_count; $g++): ?>
        <div class="group well" id="group0">
            <div class="form-group form-inline">
                <div class="search_bool">
	                <label for="search_bool<?=$g?>">Match:&nbsp;</label>
	                <select class="form-control" name="bool<?=$g?>[]" id="search_bool<?=$g?>">
	                    <?
	                        $operator = 'AND';
	                        if ($groups != false) {
	                            if ($groups[$g]->isNegated()) {
	                                $operator = 'NOT';
	                            } else {
	                                $operator = $groups[$g]->getOperator();
	                            }
	                        }
	                        foreach (array(
	                            array('value' => 'AND', 'text' => 'ALL Terms'),
	                            array('value' => 'OR', 'text' => 'ANY Terms'),
	                            array('value' => 'NOT', 'text' => 'NO Terms'),
	                        ) as $option): 
	                            $selected = '';
	                            if ($option['value'] == $operator) {
	                                $selected = 'selected="selected" ';
	                            }
	                            $value = $option['value'];
	                            $text = $option['text'];
	                    ?>
	                        <option <?=$selected?>value="<?=$value?>"><?=$text?></option>
	                    <? endforeach; ?>
	                </select>
                </div><!-- end search_bool-->
            </div><!-- end form-group-->

            <? ($groups == false) ? $search_count = 3 : $search_count = count($groups[$g]->getQueries()); ?>

            <? for ($s = 0; $s < $search_count; $s++): ?>
                <div id="search<?=$g?>_<?=$s?>" class="search form-group form-inline">
                    <?php
                        $value = '';
                        if ($groups != false) {
                            $tmp = $groups[$g]->getQueries();
                            $value = $tmp[$s]->getString();
                        }
                    ?>
                    <input type="text" value="<?=$value?>" name="lookfor<?=$g?>[]" class="form-control input-large" id="search_lookfor<?=$g?>_<?=$s?>"/>
                    <select class="form-control" name="type<?=$g?>[]" id="search_type<?=$g?>_<?=$s?>">
                        <? 
                            foreach (array(
								array('value' => 'AllFields', 'text' => 'All Fields'),
								array('value' => 'Tltle', 'text' => 'Title'),
								array('value' => 'JournalTitle', 'text' => 'Journal Title'),
								array('value' => 'Author', 'text' => 'Author '),
								array('value' => 'Performer', 'text' => 'Performer'),
								array('value' => 'Subject', 'text' => 'Subject'),
								array('value' => 'CallNumber', 'text' => 'Call Number'),
								array('value' => 'StandardNumbers', 'text' => 'ISBN, ISSN, etc.'),
								array('value' => 'publisher', 'text' => 'Publisher'),
								array('value' => 'publication_place', 'text' => 'Publication Place'),
								array('value' => 'Series', 'text' => 'Series'),
								array('value' => 'year', 'text' => 'Year of Publication'),
								array('value' => 'toc', 'text' => 'Table of Contents'),
								array('value' => 'Donor', 'text' => 'Donor'),
								array('value' => 'Title Uniform', 'text' => 'Uniform Title'),
								array('value' => 'Notes', 'text' => 'Notes'),
                            ) as $o): 
                                $value = $o['value']; 
                                $text = $o['text']; 
                                $selected = '';
                                if ($groups != false) {
                                    $tmp = $groups[$g]->getQueries();
                                    if ($tmp[$s]->getHandler() == $value) {
                                        $selected = 'selected="selected" ';
                                    }
                                }
                        ?>
                            <option <?=$selected?>value="<?=$value?>"><?=$text?></option>
                        <? endforeach; ?>
                    </select>
                </div><!-- end search-->
            <? endfor; ?>

        </div><!-- end group/well-->
    <? endfor; ?>
    
          <div style="text-align: right;">
            <input class="btn btn-primary advancedSearchBtn" type="submit" value="Search"/>
          </div>
          <? if (isset($this->extraAdvancedControls)): ?>
            <?=$this->extraAdvancedControls ?>
            <div style="text-align: right;">
            <input class="btn btn-primary advancedSearchBtn" type="submit" value="Search"/>
            </div>
          <? endif; ?>
        </div>
    
        <div class="<?=$this->layoutClass('sidebar')?>">
          <? if ($hasDefaultsApplied): ?>
            <input type="hidden" name="dfApplied" value="1" />
          <? endif ?>
          <? if (!empty($searchFilters)): ?>
            <h4><?=$this->transEsc("adv_search_filters")?></h4>
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  <label><input type="checkbox" checked="checked" class="checkbox-select-all"/><?=$this->transEsc("adv_search_select_all")?></label>
                </div>
              </li>
            </ul>
            <? foreach ($searchFilters as $field => $data): ?>
            <? if (!in_array($data[0]['field'], array('language', 'format',  'building', 'item_collection'))): ?>
              <ul class="list-group">
                <li class="list-group-item title"><?=$this->transEsc($field)?></li>
                <? foreach ($data as $value): ?>
                  <li class="list-group-item"><div class="checkbox"><label><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"'
/> <?=$this->escapeHtml($value['displayText'])?></label></div></li>
                <? endforeach; ?>
              </ul>
            <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
        </div><!-- end col-md-12-->
      </div><!-- end row-->
    </form>
  </div><!-- end advSearch-->

  <div class="tab-pane" id="alphaBrowse">
    <form action="/vufind/alphabrowse/home" class="form-inline" id="alphaBrowseForm" method="get" name="alphaBrowseForm">
      <div class="row">
        <div class="col-sm-12">
          <div class="well">
            <div style="margin: 15px 0;">
            <label for="alphaBrowseForm_from" class="offscreen">starting from</label>
            <input class="form-control input-large" type="text" value="" id="alphaBrowseForm_from" name="from" placeholder="a manual for writers of">
            
            <label for="alphaBrowseForm_source" class="offscreen">Browse Alphabetically</label>
            <select class="form-control" id="alphaBrowseForm_source" name="source">
              <option value="title">Title</option>
              <option value="author">Author</option>
              <option value="topic">Subject</option>
              <option value="journal">Journal</option>
              <option value="series">Series</option>
              <option value="lcc">Call Number</option>
            </select>
    
            <input type="submit" value="Browse" class="btn btn-primary">
          </div><!--end form-group-->
          </div><!--end well--> 
        </div><!-- end col-sm-12-->
      </div><!-- end row-->
    </form>
  </div><!-- end alphaBrowse-->
</div><!-- end tab-content-->

<div class="row">
  <div class="col-md-12">
    <div id="about-beta"> 
      <p class="title">
        <a href="http://www.lib.uchicago.edu/e/using/catalog/about.html" target="_blank" class="external">About the Library Catalog</a>
      </p>
    </div><!-- end about-beta-->
  </div><!-- end col-md-12-->
</div><!-- end row-->


