<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
  }

  // Set up Javascript:
  // Step 1: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  // Step 2: Call the javascript to make use of the above
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  // Step 3: Build the page
  $this->headScript()->appendScript(
    $this->partial(
      isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
      array('searchDetails' => $searchDetails)
    )
  );
?>

<?=$this->flashmessages()?>

<ul style="position: relative; top: 1px;" class="nav nav-tabs" id="homepageNavTabs">
  <li style="position: relative; top: 0px;" class="active"><a data-toggle="tab" href="#advSearch">Keyword</a></li>
  <li role="presentation"><a data-toggle="tab" href="#alphaBrowse">Begins With</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="advSearch">
    <form role="search" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
      <div class="row">
        <div class="col-sm-9">
          <input type="hidden" name="sort" value="relevance">
          <div class="clearfix">
            <div id="groupJoin" class="form-inline pull-right hidden">
              <label for="groupJoinOptions"><?=$this->transEsc("search_match")?>:</label>
              <select id="groupJoinOptions" name="join" class="form-control">
                <option value="AND"<? if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
                <option value="OR"<? if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
              </select>
            </div>
          </div>
    
    <div class="group well" id="group0">
    
          <div class="form-group form-inline">
            <label for="search_bool0">Match:&nbsp;</label>
            <a title="Remove Search Group" class="close hidden" onclick="deleteGroup(this)" href="#">×</a>
            <select class="form-control" name="bool0[]" id="search_bool0">
              <option value="AND">ALL Terms</option>
              <option value="OR">ANY Terms</option>
              <option value="NOT">NO Terms</option>
            </select>
          </div><!-- end form-group-->
    
            <div id="search0_0" class="search form-group form-inline">
              <input type="text" value="" name="lookfor0[]" class="form-control input-large" id="search_lookfor0_0" placeholder="evolutionary biology">
              <select class="form-control" name="type0[]" id="search_type0_0">
                <option value="AllFields">All Fields</option>
                <option value="Title">Title</option>
                <option value="Author">Author</option>
                <option value="Subject">Subject</option>
                <option value="JournalTitle">Journal Title</option>
                <option value="StandardNumbers">ISBN, ISSN, etc.</option>
                <option value="Series">Series</option>
                <option value="Publisher">Publisher</option>
              </select>
              <a onclick="deleteSearch(this)" href="#" class="delete">×</a>
              <input class="btn btn-primary basicSearchBtn" type="submit" value="Search"/>
            </div><!-- end search0_0-->
          <div id="search0_1" class="search form-group form-inline">
            <input type="text" value="" name="lookfor0[]" class="form-control input-large" id="search_lookfor0_1" placeholder="evolutionary biology">
              <select class="form-control" name="type0[]" id="search_type0_1">
                <option value="AllFields">All Fields</option>
                <option value="Title">Title</option>
                <option value="Author">Author</option>
                <option value="Subject">Subject</option>
                <option value="JournalTitle">Journal Title</option>
                <option value="StandardNumbers">ISBN, ISSN, etc.</option>
                <option value="Series">Series</option>
                <option value="Publisher">Publisher</option>
              </select>
            <a onclick="deleteSearch(this)" href="#" class="delete">×</a>
          </div><!-- end search0_1-->
            <div id="search0_2" class="search form-group form-inline">
              <input type="text" value="" name="lookfor0[]" class="form-control input-large" id="search_lookfor0_2" placeholder="evolutionary biology"/>
              <select class="form-control" name="type0[]" id="search_type0_2">
                <option value="AllFields">All Fields</option>
                <option value="Title">Title</option>
                <option value="Author">Author</option>
                <option value="Subject">Subject</option>
                <option value="JournalTitle">Journal Title</option>
                <option value="StandardNumbers">ISBN, ISSN, etc.</option>
                <option value="Series">Series</option>
                <option value="Publisher">Publisher</option>
              </select>
              <a onclick="deleteSearch(this)" href="#" class="delete">×</a>
            </div><!-- end search 0_2-->
          <i class="fa fa-plus-circle" id="group0Holder" style="display: inline-block;"></i> 
          <a onclick="addSearch(this)" id="add_search_link_0" href="#" style="display: inline;">Add Search Field</a> 
          <a class="external" id="what_is_a_field" href="http://www.lib.uchicago.edu/e/using/catalog/help.html#searchfield" style="display: inline;"><i class="icon-info-sign icon-large" style="text-decoration: none;"></i>What is a Field?</a>
          <p id="advSearchP">
            <a href="http://www.lib.uchicago.edu/e/using/catalog/help.html#powersearch" class="external">Power searching instructions (Boolean, etc.)</a>
          </p>
    </div><!-- end group/well-->
    
    
    
    
    
    
          <div id="groupPlaceHolder">
            <i class="fa fa-plus-circle"></i> <a href="#" onClick="addGroup()"><?= $this->transEsc('add_search_group') ?></a>
       <a href="http://www.lib.uchicago.edu/e/using/catalog/help.html#searchgroup" id="what_is_a_group" target="_blank" class="external">
         <i style="text-decoration: none;" class="icon-info-sign icon-l arge"></i>What is a Group?
       </a>
          </div>
          <div style="text-align: right;">
            <input class="btn btn-primary advancedSearchBtn" type="submit" value="Search"/>
          </div>
          <? if (isset($this->extraAdvancedControls)): ?>
            <?=$this->extraAdvancedControls ?>
            <div style="text-align: right;">
            <input class="btn btn-primary advancedSearchBtn" type="submit" value="Search"/>
            </div>
          <? endif; ?>
        </div>
    
        <div class="<?=$this->layoutClass('sidebar')?>">
          <? if ($hasDefaultsApplied): ?>
            <input type="hidden" name="dfApplied" value="1" />
          <? endif ?>
          <? if (!empty($searchFilters)): ?>
            <h4><?=$this->transEsc("adv_search_filters")?></h4>
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  <label><input type="checkbox" checked="checked" class="checkbox-select-all"/><?=$this->transEsc("adv_search_select_all")?></label>
                </div>
              </li>
            </ul>
            <? foreach ($searchFilters as $field => $data): ?>
            <? if (!in_array($field, array('Language', 'Format'))): ?>
              <ul class="list-group">
                <li class="list-group-item title"><?=$this->transEsc($field)?></li>
                <? foreach ($data as $value): ?>
                  <li class="list-group-item"><div class="checkbox"><label><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"'
/> <?=$this->escapeHtml($value['displayText'])?></label></div></li>
                <? endforeach; ?>
              </ul>
            <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
        </div><!-- end col-md-12-->
      </div><!-- end row-->
    </form>
  </div><!-- end advSearch-->

  <div class="tab-pane" id="alphaBrowse">
    <form action="/vufind/alphabrowse/home" class="form-inline" id="alphaBrowseForm" method="get" name="alphaBrowseForm">
      <div class="row">
        <div class="col-sm-9">
          <div class="well">
            <div style="margin: 15px 0;">
            <label for="alphaBrowseForm_from" class="offscreen">starting from</label>
            <input class="form-control input-large" type="text" value="" id="alphaBrowseForm_from" name="from" placeholder="a manual for writers of">
            
            <label for="alphaBrowseForm_source" class="offscreen">Browse Alphabetically</label>
            <select class="form-control" id="alphaBrowseForm_source" name="source">
              <option value="title">Title</option>
              <option value="author">Author</option>
              <option value="topic">Subject</option>
              <option value="journal">Journal</option>
              <option value="series">Series</option>
              <option value="lcc">Call Number</option>
              <option value="dewey">Dewey Call Number</option>
            </select>
    
            <input type="submit" value="Browse" class="btn btn-primary">
          </div><!--end form-group-->
          </div><!--end well--> 
        </div><!-- end col-md-12-->
      </div><!-- end row-->
    </form>
  </div><!-- end alphaBrowse-->
</div><!-- end tab-content-->

<div class="row">
  <div class="col-md-12">
    <div id="about-beta"> 
      <p class="title">
        <a href="http://www.lib.uchicago.edu/e/using/catalog/about.html" target="_blank" class="external">About the Library Catalog</a>
      </p>
      <ul>
        <li><a href="http://www.lib.uchicago.edu/e/using/catalog/about.html" target="_blank" class="external">Features</a></li>
        <li><a href="http://www.lib.uchicago.edu/e/using/catalog/about.html" target="_blank" class="external">Coming soon</a></li>
        <li><a href="http://www.lib.uchicago.edu/e/using/catalog/mydiscoveries-migration-2014.html" target="_blank" class="external">Migrating your Lens MyDiscoveries</a></li>
      </ul>
    </div><!-- end about-beta-->
  </div><!-- end col-md-12-->
</div><!-- end row-->
