<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>';
  $lastSearchLink = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'));
  $this->layout()->breadcrumbs .= !empty($lastSearchLink)
    ? $lastSearchLink : $this->transEsc('Search');
  $this->layout()->breadcrumbs .= '</li> <li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
    $hiddenFilters = $this->saved->getParams()->getHiddenFilters();

    // When editing an advanced search, this page displays facets in the
    // sidebar. unset the facets that get displayed as limits. 
    unset($searchFilters['Language']);
    unset($searchFilters['Format']);
    unset($searchFilters['Location']);
    unset($searchFilters['unrecognized_facet_label']);
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
    $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, true);
  }

  // Step 1: Load the javascript
  // Step 1: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  // Step 2: Build the page
  if ($this->buildPageOverride) {
    $this->headScript()->appendScript(
      $this->partial(
        $this->buildPageOverride, 
        ['options' => $this->options, 'searchDetails' => $searchDetails]
      )
    );
  }

  // Collect previous search queries
  $setSearchGroups = [];
  $setGroupCount = 0;
  $setQueries = [];
  if (isset($searchDetails) && is_object($searchDetails)) {
    foreach ($searchDetails->getQueries() as $group => $searchGroup) {
      $setSearchGroups[$group] = $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator();
      if ($setGroupCount < $group) {
        $setGroupCount = $group;
      }
      if (!isset($setQueries[$group])) {
        $setQueries[$group] = [];
      }
      foreach ($searchGroup->getQueries() as $search) {
        $setQueries[$group][] = $search;
      }
    }
  }
?>

<?=$this->flashmessages()?>

<ul style="position: relative; top: 1px;" class="nav nav-tabs" id="homepageNavTabs">
  <li style="position: relative; top: 0px;" class="active"><a data-toggle="tab" href="#advSearch">Keyword</a></li>
  <li role="presentation"><a data-toggle="tab" href="#alphaBrowse">Begins With</a></li>
  <li class="hidden-xs which-search-links">
    <a href="#" id="searchtabinfolink" data-original-title="">Which one? <i class="fa fa-lg fa-info-circle"></i></a> <a href="https://goo.gl/TqhhYd">Video</a>
  </li>
</ul>

<div class="tab-content" id="homepageNavContent">
  <div class="tab-pane active" id="advSearch">
    <form role="search" class="advancedSearch" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
      <div class="row">
        <?php if (empty($searchFilters)): ?>
        <div class="col-sm-12">
        <?php else: ?>
        <div class="col-sm-9">
        <?php endif; ?>
          <input type="hidden" name="sort" value="relevance">
          <div class="clearfix">
            <div id="groupJoin" class="form-inline hidden">
              <label for="groupJoinOptions"><?=$this->transEsc("search_match")?>:</label>
              <select id="groupJoinOptions" name="join" class="form-control">
                <option value="AND"<?php if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
                <option value="OR"<?php if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
              </select>
            </div>
          </div>

    <?php ($groups == false) ? $group_count = 1 : $group_count = count($groups); ?>
    <?php for ($g = 0; $g < $group_count; $g++): ?>
        <div class="group well" id="group<?=$g?>">
            <div class="form-group form-inline">
                <div class="search_bool">
	                <label for="search_bool<?=$g?>">Match:&nbsp;</label>
	                <select class="form-control" name="bool<?=$g?>[]" id="search_bool<?=$g?>">
	                    <?
	                        $operator = 'AND';
	                        if ($groups != false) {
	                            if ($groups[$g]->isNegated()) {
	                                $operator = 'NOT';
	                            } else {
	                                $operator = $groups[$g]->getOperator();
	                            }
	                        }
	                        foreach ([
	                            ['value' => 'AND', 'text' => 'ALL Terms'],
	                            ['value' => 'OR', 'text' => 'ANY Terms'],
	                            ['value' => 'NOT', 'text' => 'NO Terms'],
	                        ] as $option): 
	                            $selected = '';
	                            if ($option['value'] == $operator) {
	                                $selected = 'selected="selected" ';
	                            }
	                            $value = $option['value'];
	                            $text = $option['text'];
	                    ?>
	                        <option <?=$selected?>value="<?=$value?>"><?=$text?></option>
	                    <?php endforeach; ?>
	                </select>
                </div><!-- end search_bool-->
            </div><!-- end form-group-->

            <?php ($groups == false) ? $search_count = 3 : $search_count = count($groups[$g]->getQueries()); ?>

            <?php for ($s = 0; $s < $search_count; $s++): ?>
                <div id="search<?=$g?>_<?=$s?>" class="search form-group form-inline">
                    <?php
                        $value = '';
                        if ($groups != false) {
                            $tmp = $groups[$g]->getQueries();
                            $value = $tmp[$s]->getString();
                        }
                    ?>
                    <input type="text" value="<?=$value?>" name="lookfor<?=$g?>[]" class="form-control input-large" id="search_lookfor<?=$g?>_<?=$s?>"/>
                    <select class="form-control" name="type<?=$g?>[]" id="search_type<?=$g?>_<?=$s?>">
                        <?php 
                            foreach ([
								['value' => 'AllFields', 'text' => 'All Fields'],
								['value' => 'Tltle', 'text' => 'Title'],
								['value' => 'JournalTitle', 'text' => 'Journal Title'],
								['value' => 'Author', 'text' => 'Author '],
								['value' => 'Performer', 'text' => 'Performer'],
								['value' => 'Subject', 'text' => 'Subject'],
								['value' => 'CallNumber', 'text' => 'Call Number'],
								['value' => 'StandardNumbers', 'text' => 'ISBN, ISSN, etc.'],
								['value' => 'publisher', 'text' => 'Publisher'],
								['value' => 'publication_place', 'text' => 'Publication Place'],
								['value' => 'Series', 'text' => 'Series'],
								['value' => 'year', 'text' => 'Year of Publication'],
								['value' => 'toc', 'text' => 'Table of Contents'],
								['value' => 'Donor', 'text' => 'Donor'],
								['value' => 'Title Uniform', 'text' => 'Uniform Title'],
								['value' => 'Notes', 'text' => 'Notes'],
                            ] as $o): 
                                $value = $o['value']; 
                                $text = $o['text']; 
                                $selected = '';
                                if ($groups != false) {
                                    $tmp = $groups[$g]->getQueries();
                                    if ($tmp[$s]->getHandler() == $value) {
                                        $selected = 'selected="selected" ';
                                    }
                                }
                        ?>
                            <option <?=$selected?>value="<?=$value?>"><?=$text?></option>
                        <?php endforeach; ?>
                    </select>
                </div><!-- end search-->
            <?php endfor; ?>

        </div><!-- end group/well-->
    <?php endfor; ?>
    
          <div style="text-align: right;">
            <input class="btn btn-primary advancedSearchBtn" type="submit" value="Search"/>
          </div>
          <?php if (isset($this->extraAdvancedControls)): ?>
            <?=$this->extraAdvancedControls ?>
            <div style="text-align: right;">
            <input class="btn btn-primary advancedSearchBtn" type="submit" value="Search"/>
            </div>
          <?php endif; ?>
        </div>
    
        <div class="<?=$this->layoutClass('sidebar')?>">
          <?php if ($hasDefaultsApplied): ?>
            <input type="hidden" name="dfApplied" value="1" />
          <?php endif ?>
          <?php if (!empty($searchFilters)): ?>
            <h4><?=$this->transEsc("adv_search_filters")?></h4>
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  <label><input type="checkbox" checked="checked" class="checkbox-select-all"/><?=$this->transEsc("adv_search_select_all")?></label>
                </div>
              </li>
            </ul>
            <?php foreach ($searchFilters as $field => $data): ?>
            <?php if (!in_array($data[0]['field'], ['language', 'format',  'building', 'item_collection'])): ?>
              <ul class="list-group">
                <li class="list-group-item title"><?=$this->transEsc($field)?></li>
                <?php foreach ($data as $value): ?>
                  <li class="list-group-item"><div class="checkbox"><label><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"'
/> <?=$this->escapeHtml($value['displayText'])?></label></div></li>
                <?php endforeach; ?>
              </ul>
            <?php endif; ?>
            <?php endforeach; ?>
          <?php endif; ?>
        </div><!-- end col-md-12-->
      </div><!-- end row-->
    </form>
  </div><!-- end advSearch-->

  <div class="tab-pane" id="alphaBrowse">
    <form action="/vufind/alphabrowse/home" class="form-inline" id="alphaBrowseForm" method="get" name="alphaBrowseForm">
      <div class="row">
        <div class="col-sm-12">
          <div class="well">
            <div style="margin: 15px 0;">
            <label for="alphaBrowseForm_from" class="offscreen">starting from</label>
            <input class="form-control input-large" type="text" value="" id="alphaBrowseForm_from" name="from" placeholder="a manual for writers of">
            
            <label for="alphaBrowseForm_source" class="offscreen">Browse Alphabetically</label>
            <select class="form-control" id="alphaBrowseForm_source" name="source">
              <option value="title">Title</option>
              <option value="author">Author</option>
              <option value="topic">Subject</option>
              <option value="journal">Journal</option>
              <option value="series">Series</option>
              <option value="lcc">Call Number</option>
            </select>
    
            <input type="submit" value="Browse" class="btn btn-primary">
          </div><!--end form-group-->
          </div><!--end well--> 
        </div><!-- end col-sm-12-->
      </div><!-- end row-->
    </form>
  </div><!-- end alphaBrowse-->
</div><!-- end tab-content-->

<div class="row">
  <div class="col-md-12">
    <div id="about-beta"> 
      <p class="title">
        <a href="https://www.lib.uchicago.edu/research/help/catalog-help/about/" target="_blank" class="external">About the Library Catalog</a>
      </p>
    </div><!-- end about-beta-->
  </div><!-- end col-md-12-->
</div><!-- end row-->


