<?php ### UChicago customization ### ?>
<?php $itemStatusWhitelist = ['In process', 'On order']; ?>
<?php if (strlen($holding['barcode'] ?? '') > 0 || (in_array($holding['status'], $itemStatusWhitelist))): ?>
<?php ### ./UChicago customization ### ?>
  <?php
    $check = $holding['check'] ?? false;
    $checkStorageRetrievalRequest = $holding['checkStorageRetrievalRequest'] ?? false;
    $checkILLRequest = $holding['checkILLRequest'] ?? false;
    ### UChicago customization ###
    $recordTitle = $this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection());
    $cleanTitle = trim($recordTitle, ' /.');
    ### ./UChicago customization ###
  ?>
  <tr vocab="http://schema.org/" typeof="Offer">
    <? ### UChicago customization ### ?>
    <th class="copy-number"><?=$this->escapeHtml($holding['number'])?>
    <? ### ./UChicago customization ### ?>
      <?php if ($holding['enumchron'] ?? false): ?>
        <span class="enumchron">(<?=$this->escapeHtml($holding['enumchron'])?>)</span>
      <?php endif; ?>         
    </th>
    <td>
      <?php if ($holding['reserve'] == "Y"): ?>
        <link property="availability" href="http://schema.org/InStoreOnly" />
        <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
      <?php endif; ?>
      <?php if ($holding['use_unknown_message'] ?? false): ?>
        <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
      <?php else: ?>
        <?php if ($holding['availability'] ?? false): ?>
          <?php /* Begin Available Items (Holds) */ ?>
          <? ### UChicago customization ### ?>
          <span class="text-success <?=$holding['hide_status'] ? 'hide' : ''?>"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" />
            <?php if (isset($holding['loan_type_id']) && !empty($holding['loan_type_name'])):?>
              <span class="loan-period">Loan period: <?=$holding['loan_type_name']?>&nbsp;</span>
            <?endif;?>
          </span>
          <? ### ./UChicago customization ### ?>
          <?php if ($holding['link'] ?? false): ?>
            <? ### UChicago customization ### ?>
            <!--<a class="<?//=$check ? 'checkRequest ' : ''?>placehold" <?php //if (!empty($holding['linkLightbox'])): ?>data-lightbox <?php //endif; ?>href="<?//=$this->recordLink()->getRequestUrl($holding['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?//=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>-->
            <? ### ./UChicago customization ### ?>
          <?php endif; ?>
          <?php if ($holding['storageRetrievalRequestLink'] ?? false): ?>
            <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holding['storageRetrievalRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
          <?php endif; ?>
          <?php if ($holding['ILLRequestLink'] ?? false): ?>
            <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holding['ILLRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
          <?php endif; ?>
        <?php else: ?>
          <?php /* Begin Unavailable Items (Recalls) */ ?>
          <? ### UChicago customization ### ?>
          <?php // Analytic record ?>
          <?php if ($holding['item_statistical_code'] == '27da80dc-b1de-5719-8326-18c3a41dfc3c'):?>
            To check availability
            <?php $callNumBreak = preg_split("/\s[a-zA-Z0-9]+\./", $holding['callnumber']); ?>
            <?php if ($callNumBreak): ?>
              <?php $c = $callNumBreak[0]; ?>
            <?php else: ?>
              <?php $c = $callNos['sort'][$numKey]; ?>
            <?php endif; ?>
            <a href="/vufind/alphabrowse/home?from=<?=$c;?>&source=lcc&consult=true">consult the series record</a>.
          <?php endif; ?>
          <span class="text-danger <?=$holding['hide_status'] ? 'hide' : ''?>"><?=$this->transEsc($holding['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
          <? ### ./UChicago customization ### ?>
          <?php if ($holding['returnDate'] ?? false): ?>&ndash; <span class="small"><?=$this->escapeHtml($holding['returnDate'])?></span><?php endif; ?>
          <?php if ($holding['duedate'] ?? false): ?>
            &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($holding['duedate'])?></span>
          <?php endif; ?>
          <?php if (($holding['requests_placed'] ?? 0) > 0): ?>
            <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($holding['requests_placed'])?></span>
          <?php endif; ?>
          <?php if ($holding['link'] ?? false): ?>
            <? ### UChicago customization ### ?>
            <!--<a class="<?//=$check ? 'checkRequest' : ''?> placehold" <?php //if (!empty($holding['linkLightbox'])): ?>data-lightbox <?php //endif; ?>href="<?//=$this->recordLink()->getRequestUrl($holding['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?//=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>-->
            <? ### ./UChicago customization ### ?>
          <?php endif; ?>
          <?=$this->relais()->renderButtonIfActive($this->driver ?? null)?>
        <?php endif; ?>
        <? ### UChicago customization ### ?>
        <span class="service-links">
          <?=$this->ServiceLinks()->hold($holding)?>
          <?=$this->ServiceLinks()->mansueto($holding)?>
          <?=$this->ServiceLinks()->ill($holding)?>
          <?=$this->ServiceLinks()->scrc($holding)?>
          <?=$this->ServiceLinks()->alttext($this->driver->getFormats(), $this->driver->getUniqueID(), $holding)?>
          <?=$this->ServiceLinks()->scanAndDeliver($holding)?>
          <?=$this->ServiceLinks()->offsite($holding)?>
          <?=$this->ServiceLinks()->paging($holding)?>
          <?=$this->ServiceLinks()->ask($holding, $cleanTitle)?>
          <?=$this->ServiceLinks()->askSCRC($holding)?>
          <?=$this->ServiceLinks()->itemServlet($holding)?>
        </span>
        <? ### ./UChicago customization ### ?>
        <? ### UChicago customization ### ?>
        <?php if ($holding['holding_location'] != $holding['location']): ?>
          <span class="location-change">
              <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
              <strong>Shelved in:</strong> <?=$holding['location'];?>
          </span>
        <?php endif; ?>
        <? ### ./UChicago customization ### ?>
        <? ### UChicago customization ### ?>
        <?php $itemCallnumDisplay = $holding['callnumber_prefix'] ?
            $holding['callnumber_prefix'] . ' ' . $holding['callnumber'] :
            $holding['callnumber'];?>
        <?php $holdingCallnumDisplay = $holding['holding_callnumber_prefix'] ?
            $holding['holding_callnumber_prefix'] . ' ' . $holding['holding_callnumber'] :
            $holding['holding_callnumber'];?>
        <?php if ($itemCallnumDisplay != $holdingCallnumDisplay): ?>
          <span class="location-change">
            <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
            <strong>Shelved as:</strong>
            <?=$itemCallnumDisplay;?>
          </span>
        <?php endif; ?>
        <? ### ./UChicago customization ### ?>
        <?php if (isset($holding['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc("Item Notes")?>:</b>
            <ul>
              <?php foreach ($holding['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      <?php endif; ?>
      <?php /* Embed item structured data: library, barcode, call number */ ?>
      <?php if ($holding['location'] ?? false): ?>
        <meta property="seller" content="<?=$this->escapeHtmlAttr($holding['location'])?>" />
      <?php endif; ?>
      <?php if ($holding['barcode'] ?? false): ?>
        <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($holding['barcode'])?>" />
      <?php endif; ?>
      <?php if ($holding['callnumber'] ?? false): ?>
        <meta property="sku" content="<?=$this->escapeHtmlAttr($holding['callnumber'])?>" />
      <?php endif; ?>
      <?php /* Declare that the item is to be borrowed, not for sale */ ?>
      <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
      <link property="itemOffered" href="#record" />
    </td>
  </tr>
<?php endif; ?>
